const V={key:'vertex_flux_2',data:null,screen:'dashboard',sector:'all'};
const seed={pin:'2580',clients:[{id:1,name:'ABC Emlak',sector:'emlak',status:'Aktif'},{id:2,name:'Çoban Diamond',sector:'kuyum',status:'Aktif'},{id:3,name:'Vertex Resort',sector:'otel',status:'Kurulum'}],jobs:[{id:'VF-2401',title:'Lara 2+1 360°',client:'ABC Emlak',sector:'emlak',status:'Planlandı',date:'2026-09-22'},{id:'VF-2402',title:'Ürün çekimi',client:'Çoban Diamond',sector:'kuyum',status:'Düzenleniyor',date:'2026-09-23'}],properties:[{id:1,client:'ABC Emlak',name:'Lara 2+1',sqm:115,floor:'Tek kat',tour:'Aktif',qr:'Aktif',status:'Satılık',scans:247,views:613}],tasks:[{title:'Lara 2+1 çekim',date:'22 Eyl · 10:00',kind:'Çekim'},{title:'Çoban Diamond ürün çekimi',date:'23 Eyl · 13:00',kind:'Kuyum'}],market:[{sector:'Emlak',service:'360° Sanal Tur',low:'—',avg:'Araştırılıyor',high:'—',vertex:'Belirlenecek',source:'Kaynak bekleniyor'}],costs:[{name:'Kuula',type:'Yıllık',amount:0,sector:'Emlak/Otel'},{name:'Short.io',type:'Aylık',amount:0,sector:'Ortak'}],health:[{name:'ABC Emlak · Lara 2+1',qr:'OK',redirect:'OK',provider:'OK',last:'Henüz otomatik test yok'}],audit:[]};
function load(){try{V.data=JSON.parse(localStorage.getItem(V.key))||structuredClone(seed)}catch{V.data=structuredClone(seed)}}
function save(action){localStorage.setItem(V.key,JSON.stringify(V.data));if(action){V.data.audit.unshift({at:new Date().toLocaleString('tr-TR'),action});localStorage.setItem(V.key,JSON.stringify(V.data))}}
const icons={dashboard:'⌂',quotes:'⌁',jobs:'✓',calendar:'◷',clients:'◎',properties:'⌂',market:'↗',gallery:'▦',costs:'₺',health:'●',admin:'⚙'};
function nav(){return [['dashboard','Panel'],['quotes','Teklifler'],['jobs','İşler'],['calendar','Takvim / Görevler'],['clients','Müşteriler'],['properties','Mülkler'],['market','Piyasa'],['gallery','Örnek Galeri'],['costs','Maliyet Merkezi'],['health','Sistem Sağlığı'],['admin','Uzaktan Yönetim']].map(([k,t])=>'<button class="'+(V.screen===k?'active':'')+'" onclick="go(\''+k+'\')">'+icons[k]+' <span>'+t+'</span></button>').join('')}
function layout(body,title,sub='VERTEX SUPER ADMIN'){return '<div class="shell"><aside class="side"><div class="brand"><div class="brand-mark"><img src="'+VERTEX_LOGO+'" alt="Vertex Flux"></div><div><b>VERTEX</b><small>FLUX 2.0</small></div></div><div class="nav">'+nav()+'<div class="sep"></div><button onclick="presentation()">▣ <span>Müşteri Sunumu</span></button><button onclick="logout()">⇥ <span>Kilitle</span></button></div></aside><main class="main"><div class="top"><div><div class="eyebrow">'+sub+'</div><h1>'+title+'</h1></div><div class="actions"><button class="btn" onclick="backup()">Yedek Al</button><button class="btn primary" onclick="newQuote()">+ Yeni Teklif</button></div></div>'+body+'</main></div>'}
function sectorCards(){const cards=[['emlak','EMLAK','360° Portföy Yönetimi','Mülk · 360° Tur · QR · Portföy','🏙'],['kuyum','KUYUM','Premium Ürün Deneyimi','Mücevher · Görsel · Video · Dijital Mağaza','◆'],['otel','OTEL & TURİZM','Mekân Deneyimi','Tesis · Oda · 360° · Drone · QR','✦']];return '<div class="sector-grid">'+cards.map(function(c,i){return '<button type="button" class="sector-card sector-'+c[0]+' '+(V.sector===c[0]?'selected':'')+'" data-sector="'+c[0]+'" onclick="setSector(this.dataset.sector)"><div class="sector-visual"><span class="sector-symbol">'+c[4]+'</span><span class="sector-number">0'+(i+1)+'</span></div><div class="sector-copy"><span class="sector-kicker">'+c[2]+'</span><h3>'+c[1]+'</h3><p>'+c[3]+'</p><span class="sector-enter">'+(V.sector===c[0]?'SEÇİLDİ ✓':'ÇALIŞMA ALANINA GİR →')+'</span></div></button>'}).join('')+'</div>'}
function dashboard(){let b='<div class="grid stats"><div class="card stat"><span>Aktif müşteri</span><strong>'+V.data.clients.length+'</strong></div><div class="card stat"><span>Devam eden iş</span><strong>'+V.data.jobs.length+'</strong></div><div class="card stat"><span>Aktif mülk</span><strong>'+V.data.properties.length+'</strong></div><div class="card stat"><span>Sistem sağlığı</span><strong class="ok">İyi</strong></div></div>'+sectorCards()+'<div class="grid cols" style="margin-top:20px"><div class="card"><div class="section-title"><h2>Yaklaşan işler</h2></div><div class="list">'+V.data.tasks.map(x=>'<div class="row"><b>'+x.title+'</b><span>'+x.date+'</span><span class="pill">'+x.kind+'</span><span>›</span></div>').join('')+'</div></div><div class="card"><div class="section-title"><h2>Kontrol Merkezi</h2></div><p class="muted">Üç sektör birbirinden ayrı veri ve özellik kümeleriyle yönetilir.</p><div class="notice">Merkezi bulut veritabanı ve gerçek API bağlantıları sonraki altyapı aşamasında etkinleştirilecek. Bu dal şu an güvenli yönetim arayüzü prototipidir.</div></div></div>';return layout(b,'Kontrol Merkezi')}
function jobs(){let steps=['Kabul edildi','Planlandı','Çekildi','Düzenleniyor','Müşteri onayı','Teslim edildi','Ödeme bekliyor','Ödendi'];let rows=V.data.jobs.map(j=>'<div class="card"><div class="section-title"><h2>'+j.id+' · '+j.title+'</h2><span class="pill">'+j.sector.toUpperCase()+'</span></div><p>'+j.client+' · '+j.date+'</p><div class="timeline">'+steps.map(s=>'<div class="step '+(s===j.status?'done':'')+'">'+s+'</div>').join('')+'</div></div>').join('');return layout('<div class="list">'+rows+'</div>','İşler','TEKLİFTEN TESLİMATA')}
function properties(){let rows=V.data.properties.map(p=>'<div class="row"><b>'+p.name+'<br><small class="muted">'+p.client+'</small></b><span>'+p.sqm+' m² · '+p.floor+'</span><span><span class="ok">● '+p.tour+'</span><br><small>QR '+p.qr+' · '+p.scans+' tarama</small></span><button class="btn" onclick="propertyDetail('+p.id+')">Yönet</button></div>').join('');return layout('<div class="grid cols"><div class="card"><div class="section-title"><h2>Emlak Mülkleri</h2><button class="btn primary" onclick="addProperty()">+ Mülk Ekle</button></div><div class="list">'+(rows||'<span class="muted">Henüz mülk yok.</span>')+'</div></div><div class="card"><h2>Portföy Özeti</h2><p class="muted">Her mülk; çekim, 360 tur, QR, görüntülenme ve satış/kiralama durumuyla ayrı izlenir.</p><div class="stat"><span>Toplam mülk</span><strong>'+V.data.properties.length+'</strong></div></div></div>','Mülkler','EMLAK · PORTFÖY YÖNETİMİ')}
function calendar(){return layout('<div class="grid cols"><div class="card"><div class="section-title"><h2>Takvim</h2></div><div class="list">'+V.data.tasks.map(t=>'<div class="row"><b>'+t.date+'</b><span>'+t.title+'</span><span class="pill">'+t.kind+'</span><span>›</span></div>').join('')+'</div></div><div class="card"><h2>Yeni görev</h2><div class="form"><label>Görev<input id="taskTitle"></label><label>Tarih / saat<input id="taskDate"></label></div><button class="btn primary" style="margin-top:14px" onclick="addTask()">Görev Ekle</button></div></div>','Takvim / Yapılacaklar')}
function market(){return layout('<div class="toolbar"><button class="active">Fiyatlar</button><button>Rakipler</button><button>Karşılaştır</button><button>Kaynaklar</button></div><div class="card"><div class="row"><b>Hizmet</b><b>Piyasa</b><b>VERTEX</b><b>Kaynak</b></div>'+V.data.market.map(m=>'<div class="row"><span>'+m.service+'<br><small class="muted">'+m.sector+'</small></span><span>'+m.avg+'</span><span>'+m.vertex+'</span><span class="warn">'+m.source+'</span></div>').join('')+'<div class="notice">Müşteri Sunum Modu maliyet, kâr ve özel kaynak notlarını göstermez.</div></div>','Piyasa','SADECE SUPER ADMIN')}
function costs(){return layout('<div class="grid stats"><div class="card stat"><span>Aylık sabit gider</span><strong>—</strong></div><div class="card stat"><span>Değişken gider</span><strong>—</strong></div><div class="card stat"><span>Müşteri başı maliyet</span><strong>—</strong></div><div class="card stat"><span>Brüt marj</span><strong>—</strong></div></div><div class="card"><div class="row"><b>Servis</b><b>Tip</b><b>Sektör</b><b>Tutar</b></div>'+V.data.costs.map(c=>'<div class="row"><span>'+c.name+'</span><span>'+c.type+'</span><span>'+c.sector+'</span><span>'+c.amount+' TL</span></div>').join('')+'</div>','Maliyet Merkezi','GİZLİ · SUPER ADMIN')}
function health(){return layout('<div class="card"><div class="section-title"><h2>Aktif servis kontrolleri</h2><button class="btn" onclick="healthCheck()">Şimdi Kontrol Et</button></div>'+V.data.health.map(h=>'<div class="row"><b>'+h.name+'</b><span class="ok">QR ● '+h.qr+'</span><span class="ok">Tur ● '+h.provider+'</span><button class="btn">Müdahale</button></div>').join('')+'<div class="notice">Gerçek uzaktan sağlık kontrolü, VERTEX yönlendirme katmanı ve Kuula/Short.io entegrasyonu bağlandığında aktif olacak.</div></div>','Sistem Sağlığı')}
function clients(){let em=V.data.clients.filter(c=>c.sector==='emlak');return layout('<div class="grid cols"><div class="card"><div class="section-title"><h2>Emlak Müşterileri</h2><button class="btn primary" onclick="addClient()">+ Müşteri Ekle</button></div><div class="row"><b>Müşteri</b><b>Sektör</b><b>Durum</b><b></b></div>'+em.map(c=>'<div class="row"><b>'+c.name+'</b><span>EMLAK</span><span class="ok">● '+c.status+'</span><button class="btn" onclick="clientDetail('+c.id+')">Aç</button></div>').join('')+'</div><div class="card"><h2>CRM</h2><p class="muted">Müşteri kartında mülkler, işler, teklifler, ödemeler ve notlar birlikte tutulur.</p></div></div>','Müşteriler','EMLAK CRM')}
function admin(){return layout('<div class="grid cols"><div class="card"><h2>Uzaktan Sistem Yönetimi</h2><p class="muted">Müşteri seç → özellikleri uzaktan aç/kapat. Kritik işlemler ikinci onay ister ve işlem geçmişine yazılır.</p>'+V.data.clients.map(c=>'<div class="row"><b>'+c.name+'</b><span>'+c.sector.toUpperCase()+'</span><span class="pill">Feature Flags</span><button class="btn" onclick="toggleDemo(\''+c.name+'\')">Yönet</button></div>').join('')+'</div><div class="card"><h2>İşlem Geçmişi</h2><div class="list">'+(V.data.audit.slice(0,8).map(a=>'<div><small class="muted">'+a.at+'</small><br>'+a.action+'</div>').join('')||'<span class="muted">Henüz işlem yok.</span>')+'</div></div></div>','Uzaktan Yönetim','SUPER ADMIN')}
function quotes(){let q=V.data.quotes||[];return layout('<div class="grid cols"><div class="card"><h2>Yeni Emlak Teklifi</h2><div class="form"><label>Müşteri<select id="qClient">'+V.data.clients.filter(x=>x.sector==='emlak').map(x=>'<option>'+x.name+'</option>').join('')+'</select></label><label>Teklif tipi<select id="qType"><option>Tek Mülk</option><option>Portföy Çekimi</option><option>VERTEX 360 Üyelik</option></select></label><label>Mülk / Proje<input id="qProperty" placeholder="Örn. Lara 3+1"></label><label>m²<input id="qSqm" type="number" placeholder="150"></label><label>Hizmet<select id="qService"><option>360° Sanal Tur</option><option>360° + Drone</option><option>360° + Reels</option><option>360° + Drone + Reels</option></select></label><label>Teklif tutarı (TL)<input id="qAmount" type="number" placeholder="0"></label></div><button class="btn primary" style="margin-top:14px" onclick="createQuote()">Teklifi Kaydet</button></div><div class="card"><h2>Kayıtlı Teklifler</h2><div class="list">'+(q.map(x=>'<div class="row"><b>'+x.property+'</b><span>'+x.client+'</span><span>'+Number(x.amount).toLocaleString('tr-TR')+' TL</span><button class="btn" onclick="acceptQuote(\''+x.id+'\')">'+(x.status==='Kabul edildi'?'İş Açıldı':'Kabul Et')+'</button></div>').join('')||'<span class="muted">Henüz teklif yok.</span>')+'</div></div></div>','Emlak Teklifleri','TEKLİF → İŞ')}
function generic(title,msg){return layout('<div class="card"><h2>'+title+'</h2><p class="muted">'+msg+'</p></div>',title)}
function render(){let f={dashboard,jobs,calendar,clients,properties,market,costs,health,admin,quotes,gallery:()=>generic('Örnek Çalışma Galerisi','Emlak satış sunumunda kullanılacak 360° ve çekim örnekleri burada tutulacak.')};document.getElementById('app').innerHTML=(f[V.screen]||dashboard)()}
function go(s){V.screen=s;render()} function setSector(s){V.sector=s;sessionStorage.setItem('vf_sector',s);render()}
function addTask(){let t=document.getElementById('taskTitle').value,d=document.getElementById('taskDate').value;if(!t)return;V.data.tasks.unshift({title:t,date:d||'Tarih yok',kind:'Görev'});save('Görev eklendi: '+t);render()}
function toggleDemo(n){if(confirm(n+' için uzaktan özellik yönetimini açmak istiyor musun?')){save(n+' uzaktan yönetim ekranı açıldı');alert('Bu müşteri için özellik anahtarları altyapı bağlantısından sonra canlı yönetilecek.');render()}}
function backup(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(V.data,null,2)],{type:'application/json'}));a.download='vertex-flux-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();save('JSON yedeği alındı')}
function healthCheck(){save('Manuel sağlık kontrolü istendi');alert('QR / yönlendirme / tur katmanları için canlı kontrol altyapısı bağlanınca bu düğme gerçek test yapacak.');render()}
function uid(p){return p+'-'+Date.now().toString(36).toUpperCase()}
function addClient(){let name=prompt('Emlak müşteri / ofis adı');if(!name)return;V.data.clients.unshift({id:Date.now(),name,sector:'emlak',status:'Aktif',createdAt:new Date().toISOString()});save('Emlak müşterisi eklendi: '+name);render()}
function addProperty(){let client=prompt('Müşteri / ofis adı');if(!client)return;let name=prompt('Mülk adı (örn. Lara 3+1)');if(!name)return;let sqm=Number(prompt('Yaklaşık m²')||0);V.data.properties.unshift({id:Date.now(),client,name,sqm,floor:'—',tour:'Bekliyor',qr:'Bekliyor',status:'Aktif',scans:0,views:0});save('Mülk eklendi: '+name);render()}
function propertyDetail(id){let p=V.data.properties.find(x=>x.id===id);if(!p)return;let s=prompt('Mülk durumu',p.status||'Aktif');if(s){p.status=s;save('Mülk durumu güncellendi: '+p.name+' → '+s);render()}}
function clientDetail(id){let c=V.data.clients.find(x=>x.id===id);if(!c)return;let pc=V.data.properties.filter(x=>x.client===c.name).length,jc=V.data.jobs.filter(x=>x.client===c.name).length;alert(c.name+'\nMülk: '+pc+'\nİş: '+jc+'\nDurum: '+c.status)}
function createQuote(){V.data.quotes=V.data.quotes||[];let q={id:uid('TKL'),client:document.getElementById('qClient').value,type:document.getElementById('qType').value,property:document.getElementById('qProperty').value||'Adsız mülk',sqm:Number(document.getElementById('qSqm').value||0),service:document.getElementById('qService').value,amount:Number(document.getElementById('qAmount').value||0),status:'Bekliyor',createdAt:new Date().toISOString()};V.data.quotes.unshift(q);save('Teklif oluşturuldu: '+q.id);render()}
function acceptQuote(id){let q=V.data.quotes.find(x=>x.id===id);if(!q||q.status==='Kabul edildi')return;q.status='Kabul edildi';let prop=V.data.properties.find(x=>x.client===q.client&&x.name===q.property);if(!prop){prop={id:Date.now(),client:q.client,name:q.property,sqm:q.sqm,floor:'—',tour:'Bekliyor',qr:'Bekliyor',status:'Aktif',scans:0,views:0};V.data.properties.unshift(prop)}let jid=uid('VF');V.data.jobs.unshift({id:jid,title:q.property+' · '+q.service,client:q.client,sector:'emlak',status:'Kabul edildi',date:new Date().toLocaleDateString('tr-TR'),quoteId:q.id,propertyId:prop.id});V.data.tasks.unshift({title:q.property+' planlama',date:'Tarih belirlenecek',kind:'Çekim'});save('Teklif kabul edildi ve iş açıldı: '+jid);render()}
function newQuote(){go('quotes')}
function presentation(){document.body.insertAdjacentHTML('beforeend','<div class="presentation" id="presentation"><button class="btn close" onclick="exitPresentation()">Yöneticiye Dön</button><div class="hero"><div class="presentation-logo"><img src="'+VERTEX_LOGO+'" alt="Vertex Flux"></div><div class="eyebrow">VERTEX FLUX</div><h1>Dijital Deneyim</h1><p>Müşteriniz için doğru hizmeti birlikte seçelim.</p>'+sectorCards()+'</div></div>')}
function exitPresentation(){let p=prompt('Yönetici PIN');if(p===V.data.pin)document.getElementById('presentation').remove();else alert('PIN yanlış')}
function logout(){sessionStorage.removeItem('vf_auth');login()}
function login(){document.getElementById('app').innerHTML='<div class="login"><div class="login-ambient a"></div><div class="login-ambient b"></div><div class="loginbox"><div class="login-logo"><img src="'+VERTEX_LOGO+'" alt="Vertex Flux"></div><div class="eyebrow">VERTEX PRIVATE CONTROL SYSTEM</div><h1>FLUX <span>2.0</span></h1><p class="login-sub">Merkezi yönetim sistemine güvenli giriş</p><label class="pin-label">YÖNETİCİ PIN<input id="pin" type="password" inputmode="numeric" maxlength="6" placeholder="••••"></label><button class="btn primary login-button" onclick="auth()">Sisteme Gir <span>→</span></button><div class="login-foot"><span>● Sistem çevrimiçi</span><span>SUPER ADMIN</span></div></div></div>'}
function auth(){if(document.getElementById('pin').value===V.data.pin){sessionStorage.setItem('vf_auth','1');render()}else alert('PIN yanlış')}
load();V.sector=sessionStorage.getItem('vf_sector')||'all';if(sessionStorage.getItem('vf_auth'))render();else login();