const V={screen:'dashboard',sector:'emlak',data:{clients:[],properties:[],quotes:[],jobs:[],tasks:[],payments:[],audit:[],pricing:[]},cloudHealthy:false};
const CLOUD=window.VertexCloud;

const TR={aktif:'Aktif',pasif:'Pasif',arsiv:'Arşiv',bekliyor:'Bekliyor',kabul_edildi:'Kabul edildi',planlandi:'Planlandı',cekildi:'Çekildi',duzenleniyor:'Düzenleniyor',musteri_onayi:'Müşteri onayı',teslim_edildi:'Teslim edildi',odeme_bekliyor:'Ödeme bekliyor',odendi:'Ödendi',tamamlandi:'Tamamlandı'};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const val=id=>document.getElementById(id)?.value?.trim()||'';
function cloudErr(e){console.error(e);alert('İşlem tamamlanamadı: '+(e?.message||e))}
async function audit(action,entity='',entityId=null){try{const {data:{user}}=await CLOUD.auth.getUser();if(user)await CLOUD.from('audit_logs').insert({user_id:user.id,action,entity_type:entity,entity_id:entityId})}catch(e){console.warn(e)}}
async function loadCloud(){
 const names=['clients','properties','quotes','jobs','tasks','payments','audit_logs','pricing_settings'];
 const r=await Promise.all(names.map(n=>CLOUD.from(n).select('*').order('created_at',{ascending:false}).limit(n==='audit_logs'?50:500)));
 const bad=r.find(x=>x.error);if(bad)throw bad.error;
 const [cl,pr,qu,jo,ta,pa,au,ps]=r.map(x=>x.data||[]), cm=Object.fromEntries(cl.map(x=>[x.id,x.name]));
 V.data.clients=cl.map(x=>({...x,contact:x.contact_person}));
 V.data.properties=pr.map(x=>({...x,name:x.title,client:cm[x.client_id]||'—',type:x.property_type,tour:TR[x.tour_status]||x.tour_status,qr:TR[x.qr_status]||x.qr_status,status:TR[x.listing_status]||x.listing_status}));
 V.data.quotes=qu.map(x=>({...x,client:cm[x.client_id]||'—',amount:x.total,property:x.notes||x.quote_no||'Teklif'}));
 V.data.jobs=jo.map(x=>({...x,client:cm[x.client_id]||'—',date:x.scheduled_at?new Date(x.scheduled_at).toLocaleString('tr-TR'):'Planlanmadı'}));
 V.data.tasks=ta.map(x=>({...x,date:x.due_at?new Date(x.due_at).toLocaleString('tr-TR'):'Tarih yok'}));
 V.data.payments=pa;V.data.pricing=ps;V.data.audit=au.map(x=>({at:new Date(x.created_at).toLocaleString('tr-TR'),action:x.action}));
 V.cloudHealthy=true;
}
const icons={dashboard:'⌂',quotes:'▤',jobs:'✓',calendar:'▦',clients:'●',properties:'⌂',market:'▥',gallery:'▣',costs:'₺',pricing:'
function nav(){return [['dashboard','Panel'],['quotes','Teklifler'],['jobs','İşler'],['calendar','Takvim / Görevler'],['clients','Müşteriler'],['properties','Mülkler'],['market','Piyasa'],['gallery','Örnek Galeri'],['costs','Finans Merkezi'],['pricing','Fiyat Merkezi'],['health','Sistem Sağlığı'],['admin','Uzaktan Yönetim']].map(([k,t])=>'<button class="'+(V.screen===k?'active':'')+'" onclick="go(\''+k+'\')"><span class="ni">'+icons[k]+'</span><span>'+t+'</span></button>').join('')}
function layout(body,title,sub='VERTEX SUPER ADMIN'){const back=V.screen!=='dashboard'?'<button class="back-btn" onclick="goBack()" aria-label="Geri dön"><span>←</span> Geri</button>':'';return '<div class="shell"><aside class="side"><div class="brand"><div class="brand-mark"><img src="'+VERTEX_LOGO+'"></div><div><b>VERTEX</b><small>FLUX 2.0</small></div></div><div class="nav">'+nav()+'<div class="sep"></div><button onclick="presentation()">▣ <span>Müşteri Sunumu</span></button><button onclick="logout()">⇥ <span>Kilitle</span></button></div></aside><main class="main">'+back+'<div class="top"><div><div class="eyebrow">'+sub+'</div><h1>'+title+'</h1></div><div class="actions"><button class="btn" onclick="backup()">Yedek Al</button><button class="btn primary" onclick="newQuote()">+ Yeni Teklif</button></div></div>'+body+'</main></div>'}
function sectorCards(){const a=[['emlak','EMLAK','360° Portföy Yönetimi','Mülk · 360° Tur · QR · Portföy'],['kuyum','KUYUM','Premium Ürün Deneyimi','Mücevher · Görsel · Video · Dijital Mağaza'],['otel','OTEL & TURİZM','Mekân Deneyimi','Tesis · Oda · 360° · Drone · QR']];return '<div class="sector-grid">'+a.map((c,i)=>'<button class="sector-card sector-'+c[0]+'" onclick="openSectorWorkspace(\''+c[0]+'\')"><div class="sector-visual"><div class="sector-art">'+VERTEX_SECTOR_ART[c[0]]+'</div><span class="sector-number">0'+(i+1)+'</span></div><div class="sector-copy"><span class="sector-kicker">'+c[2]+'</span><h3>'+c[1]+'</h3><p>'+c[3]+'</p><span class="sector-enter">ÇALIŞMA ALANINA GİR →</span></div></button>').join('')+'</div>'}
function dashboard(){const d=V.data;return layout('<div class="dashboard-hero"><h2>VERTEX <span>Kontrol Merkezi</span></h2><p>Üç sektörün operasyonunu tek merkezden yönetin.</p></div><div class="grid stats"><div class="card stat"><span>Müşteri</span><strong>'+d.clients.length+'</strong></div><div class="card stat"><span>İş</span><strong>'+d.jobs.length+'</strong></div><div class="card stat"><span>Mülk</span><strong>'+d.properties.length+'</strong></div><div class="card stat"><span>Bulut</span><strong class="'+(V.cloudHealthy?'ok':'warn')+'">'+(V.cloudHealthy?'Bağlı':'Kontrol')+'</strong></div></div>'+sectorCards(),'Kontrol Merkezi')}
function goBack(){if(V.screen==='sectorWorkspace'){V.screen='dashboard';render();return}if(['clients','properties','quotes','jobs','calendar','costs','pricing','market','gallery','health','admin'].includes(V.screen)){V.screen='sectorWorkspace';render();return}V.screen='dashboard';render()}
function openSectorWorkspace(s){V.sector=s;V.screen='sectorWorkspace';render()}
function sectorWorkspace(){const cfg={emlak:['EMLAK ÇALIŞMA ALANI','360° PORTFÖY YÖNETİMİ',[['Müşteriler','clients'],['Mülkler','properties'],['Teklifler','quotes'],['İşler','jobs'],['Takvim','calendar'],['Finans','costs']]],kuyum:['KUYUM ÇALIŞMA ALANI','PREMİUM ÜRÜN DENEYİMİ',[['Müşteriler','clients'],['Ürün Görselleri','gallery'],['Reklam Filmleri','gallery'],['Teklifler','quotes'],['Takvim','calendar'],['Müşteri Sunumu','presentation']]],otel:['OTEL & TURİZM ÇALIŞMA ALANI','MEKÂN DENEYİMİ',[['Müşteriler','clients'],['360° Tesis Turu','presentation'],['Drone','presentation'],['Teklifler','quotes'],['Takvim','calendar'],['Müşteri Sunumu','presentation']]]};const d=cfg[V.sector];return layout('<div class="workspace-hero workspace-'+V.sector+'"><div class="eyebrow">'+d[1]+'</div><h2>'+d[0]+'</h2><p>Bu sektöre ait müşteri, içerik, teklif ve operasyon araçları.</p><button class="btn" onclick="go(\'dashboard\')">← Kontrol Merkezine Dön</button></div><div class="workspace-grid">'+d[2].map((a,i)=>'<button class="workspace-action" onclick="'+(a[1]==='presentation'?'presentation(\''+V.sector+'\')':'go(\''+a[1]+'\')')+'"><span>0'+(i+1)+'</span><div><b>'+a[0]+'</b><small>Aç ve yönet</small></div><i>→</i></button>').join('')+'</div>',d[0],d[1])}
function clients(){const rows=V.data.clients.filter(x=>V.sector==='emlak'?x.sector==='emlak':true).map(c=>'<div class="row"><b>'+esc(c.name)+'</b><span>'+esc((c.sector||'').toUpperCase())+'</span><span class="ok">● '+esc(TR[c.status]||c.status)+'</span><button class="btn" onclick="clientDetail(\''+c.id+'\')">Aç</button></div>').join('');return layout('<div class="card"><div class="section-title"><h2>Müşteriler</h2><button class="btn primary" onclick="addClient()">+ Müşteri Ekle</button></div><div class="list">'+(rows||'<div class="empty-state">Henüz müşteri yok.</div>')+'</div></div>','Müşteriler')}
function properties(){const rows=V.data.properties.map(p=>'<div class="row"><b>'+esc(p.name)+'<br><small class="muted">'+esc(p.client)+'</small></b><span>'+esc(p.sqm||0)+' m²</span><span>360: '+esc(p.tour)+' · QR: '+esc(p.qr)+'</span><button class="btn" onclick="propertyDetail(\''+p.id+'\')">Yönet</button></div>').join('');return layout('<div class="card"><div class="section-title"><h2>Emlak Mülkleri</h2><button class="btn primary" onclick="addProperty()">+ Mülk Ekle</button></div><div class="list">'+(rows||'<div class="empty-state">Henüz mülk yok.</div>')+'</div></div>','Mülkler','EMLAK · PORTFÖY')}
function quotes(){const rows=V.data.quotes.map(q=>'<div class="row"><b>'+esc(q.quote_no||q.property)+'</b><span>'+esc(q.client)+'</span><span>'+Number(q.total||q.amount||0).toLocaleString('tr-TR')+' ₺</span><button class="btn" '+(q.status==='kabul_edildi'?'disabled':'onclick="acceptQuote(\''+q.id+'\')"')+'>'+(q.status==='kabul_edildi'?'Kabul edildi':'Kabul Et')+'</button></div>').join('');return layout('<div class="grid cols"><div class="card"><h2>Yeni Teklif</h2><div class="form"><label>Müşteri<select id="qClient">'+V.data.clients.map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join('')+'</select></label><label>Mülk / Proje<input id="qProperty"></label><label>Hizmet<select id="qService"><option>360° Sanal Tur</option><option>Drone</option><option>Reels</option><option>360° + Drone + Reels</option></select></label><label>Tutar (TL)<input id="qAmount" type="number" min="0"></label></div><button class="btn primary" onclick="createQuote()">Teklifi Kaydet</button></div><div class="card"><h2>Kayıtlı Teklifler</h2>'+(rows||'<div class="empty-state">Henüz teklif yok.</div>')+'</div></div>','Teklifler')}
function jobs(){const steps=['kabul_edildi','planlandi','cekildi','duzenleniyor','musteri_onayi','teslim_edildi','odeme_bekliyor','odendi'];const rows=V.data.jobs.map(j=>'<div class="card"><div class="section-title"><h2>'+esc(j.title)+'</h2><span class="pill">'+esc(j.client)+'</span></div><p class="muted">'+esc(j.date)+'</p><div class="timeline">'+steps.map(s=>'<button class="step '+(j.status===s?'done':'')+'" onclick="setJobStatus(\''+j.id+'\',\''+s+'\')">'+TR[s]+'</button>').join('')+'</div></div>').join('');return layout('<div class="list">'+(rows||'<div class="empty-state">Henüz iş yok.</div>')+'</div>','İşler','TEKLİFTEN TESLİMATA')}
function calendar(){const rows=V.data.tasks.map(t=>'<div class="row"><b>'+esc(t.date)+'</b><span>'+esc(t.title)+'</span><span class="pill">'+esc(TR[t.status]||t.status)+'</span><button class="btn" onclick="completeTask(\''+t.id+'\')">Tamamla</button></div>').join('');return layout('<div class="grid cols"><div class="card"><h2>Takvim</h2>'+(rows||'<div class="empty-state">Görev yok.</div>')+'</div><div class="card"><h2>Yeni Görev</h2><div class="form"><label>Görev<input id="taskTitle"></label><label>Tarih<input id="taskDate" type="datetime-local"></label></div><button class="btn primary" onclick="addTask()">Görev Ekle</button></div></div>','Takvim / Görevler')}
function costs(){const p=V.data.payments,paid=p.filter(x=>x.status==='odendi').reduce((a,x)=>a+Number(x.amount||0),0),pending=p.filter(x=>x.status!=='odendi').reduce((a,x)=>a+Number(x.amount||0),0);return layout('<div class="grid stats"><div class="card stat"><span>Tahsil</span><strong>'+paid.toLocaleString('tr-TR')+' ₺</strong></div><div class="card stat"><span>Bekleyen</span><strong>'+pending.toLocaleString('tr-TR')+' ₺</strong></div></div><div class="card"><div class="section-title"><h2>Ödemeler</h2><button class="btn primary" onclick="addPayment()">+ Ödeme Ekle</button></div>'+p.map(x=>'<div class="row"><b>'+Number(x.amount).toLocaleString('tr-TR')+' ₺</b><span>'+esc(TR[x.status]||x.status)+'</span><span>'+esc(x.due_date||'—')+'</span><button class="btn" '+(x.status==='odendi'?'disabled':'onclick="markPayment(\''+x.id+'\')"')+'>Ödendi</button></div>').join('')+'</div>','Finans Merkezi','GİZLİ · SUPER ADMIN')}
function priceCfg(k){return (V.data.pricing.find(x=>x.key===k)||{}).value||{}}
function tl(n){return Number(n||0).toLocaleString('tr-TR',{maximumFractionDigits:0})+' ₺'}
function pricing(){const fx=priceCfg('fx'),cat=priceCfg('catalog'),ads=priceCfg('ads'),rate=Number(fx.usd_try||0);const cards=[['emlak','Emlak',cat.emlak||{}],['kuyum','Kuyum',cat.kuyum||{}],['otel','Otel',cat.otel||{}]];return layout('<div class="pricing-hero"><div><div class="eyebrow">GİZLİ YÖNETİCİ FİYAT MOTORU</div><h2>Fiyat Merkezi</h2><p>USD baz fiyatları arka planda tutun; müşteriye nihai TL fiyatı gösterin.</p></div><div class="fx-box"><label>USD / TRY<input id="fxRate" type="number" step=".0001" value="'+rate+'"></label><button class="btn primary" onclick="updateFx()">Kur ve Fiyatları Güncelle</button><small>Kaynak etiketi: '+esc(fx.source||'TCMB')+' · Son güncelleme: '+esc(fx.updated_at||'—')+'</small></div></div><div class="pricing-grid">'+cards.map(([key,title,o])=>'<div class="card price-card"><div class="section-title"><h2>'+title+'</h2><span class="pill">TL satış</span></div>'+Object.entries(o).map(([k,v])=>'<label>'+k.replaceAll('_',' ')+'<div class="dual-price"><input data-sector="'+key+'" data-key="'+k+'" type="number" value="'+Number(v||0)+'"><span>'+tl(v)+'</span></div></label>').join('')+'<button class="btn" onclick="saveCatalog()">Manuel Fiyatları Kaydet</button></div>').join('')+'</div>'+adsPanel(ads),'Fiyat Merkezi','USD BAZ · TL SATIŞ')}
function adsPanel(a){const m=a.meta||{},g=a.google||{},refs=g.reference||[];return '<div class="grid cols ad-center"><div class="card"><div class="section-title"><h2>Meta Reklam Hesaplayıcı</h2><span class="pill">Medya bütçesi ayrı</span></div><label>Reklam amacı<select id="metaObjective" onchange="calcMeta()"><option value="messages">WhatsApp / Mesaj</option><option value="engagement">Etkileşim / Beğeni</option><option value="traffic">Profil / Web Sitesi Ziyareti</option><option value="followers">Takipçi</option><option value="store">Mağaza Ziyareti</option></select></label><label>Aylık medya bütçesi <b id="metaBudgetText">'+tl(m.budget||3000)+'</b><input class="budget-slider" id="metaBudget" type="range" min="1000" max="100000" step="500" value="'+Number(m.budget||3000)+'" oninput="calcMeta()"></label><div class="forecast-note" id="metaForecast">Bütçe Meta platformuna gider. Sonuçlar açık artırma, hedef kitle, kreatif ve sezona göre değişir; garanti değildir.</div><button class="btn" onclick="saveAds()">Ayarı Kaydet</button></div><div class="card"><div class="section-title"><h2>Google Ads Referansı</h2><span class="pill">Gönderdiğiniz plan</span></div><label>Aylık bütçe<input id="googleBudget" type="number" value="'+Number(g.budget||2049)+'" oninput="calcGoogle()"></label><div id="googleForecast"></div><div class="google-ref">'+refs.map(x=>'<div><b>'+tl(x.monthly)+'</b><span>'+x.clicks_min+'–'+x.clicks_max+' tahmini tıklama</span><small>'+x.daily.toLocaleString('tr-TR')+' ₺/gün referansı</small></div>').join('')+'</div><p class="muted">Referans veriler tarihsel ekran görüntüsünden gelir; canlı Google tahmini değildir.</p></div></div>'}
function calcMeta(){const b=Number(val('metaBudget')||0);document.getElementById('metaBudgetText').textContent=tl(b)}
function calcGoogle(){const b=Number(val('googleBudget')||0),refs=priceCfg('ads').google?.reference||[];if(!refs.length)return;let near=refs.reduce((a,x)=>Math.abs(x.monthly-b)<Math.abs(a.monthly-b)?x:a,refs[0]);let scale=b/near.monthly;document.getElementById('googleForecast').innerHTML='<div class="forecast-box"><span>Referans bazlı yaklaşık aralık</span><strong>'+Math.round(near.clicks_min*scale)+'–'+Math.round(near.clicks_max*scale)+' tıklama</strong><small>Doğrusal referans hesabıdır; Google Ads canlı tahmini değildir.</small></div>'}
async function saveSetting(key,value){const {error}=await CLOUD.from('pricing_settings').upsert({key,value,updated_at:new Date().toISOString()},{onConflict:'key'});if(error)return cloudErr(error);await refresh()}
async function saveCatalog(){const old=priceCfg('catalog'),next=JSON.parse(JSON.stringify(old));document.querySelectorAll('[data-sector][data-key]').forEach(i=>{next[i.dataset.sector][i.dataset.key]=Number(i.value||0)});await saveSetting('catalog',next)}
async function updateFx(){const rate=Number(val('fxRate'));if(!rate||rate<=0)return alert('Geçerli USD/TRY kuru girin.');const cat=priceCfg('catalog');const next=JSON.parse(JSON.stringify(cat));Object.keys(next).forEach(s=>Object.keys(next[s]).forEach(k=>{const item=next[s][k];if(item&&typeof item==='object'&&item.usd) item.tl=Math.round(item.usd*rate)}));await saveSetting('fx',{usd_try:rate,source:'TCMB',updated_at:new Date().toLocaleString('tr-TR')})}
async function saveAds(){const a=priceCfg('ads');a.meta={objective:val('metaObjective'),budget:Number(val('metaBudget'))};a.google={...(a.google||{}),budget:Number(val('googleBudget'))};await saveSetting('ads',a)}
function market(){return layout('<div class="card"><h2>Piyasa Araştırması</h2><p class="muted">Doğrulanmış güncel veri eklenmeden sistem fiyat veya rakip bilgisi üretmez.</p></div>','Piyasa','SADECE SUPER ADMIN')}
function gallery(){return layout('<div class="card"><h2>Müşteri Sunum Galerisi</h2><p class="muted">Emlak, Kuyum ve Otel hizmetlerini tam ekran müşteri sunumunda inceleyin.</p><button class="btn primary" onclick="presentation(\''+V.sector+'\')">Sunumu Aç</button></div>','Örnek Galeri')}
function health(){return layout('<div class="card"><div class="section-title"><h2>Canlı Bağlantı Kontrolü</h2><button class="btn primary" onclick="healthCheck()">Şimdi Kontrol Et</button></div><p class="muted">Oturum ve tüm ana veri tabloları test edilir.</p><div class="notice">'+(V.cloudHealthy?'Supabase bağlantısı son yüklemede başarılı.':'Kontrol bekleniyor.')+'</div></div>','Sistem Sağlığı')}
function admin(){return layout('<div class="grid cols"><div class="card"><h2>Bulut Yönetimi</h2><p class="muted">Supabase Auth, RLS ve merkezi veri katmanı aktif.</p><button class="btn primary" onclick="healthCheck()">Bağlantıları Test Et</button></div><div class="card"><h2>İşlem Geçmişi</h2>'+V.data.audit.slice(0,12).map(a=>'<div><small class="muted">'+esc(a.at)+'</small><br>'+esc(a.action)+'</div>').join('')+'</div></div>','Uzaktan Yönetim','SUPER ADMIN')}
function go(s){V.screen=s;render()} function newQuote(){go('quotes')}
function render(){const f={dashboard,sectorWorkspace,clients,properties,quotes,jobs,calendar,costs,pricing,market,gallery,health,admin};document.getElementById('app').innerHTML=(f[V.screen]||dashboard)()}
function modal(title,body,actions=''){document.getElementById('vfModal')?.remove();document.body.insertAdjacentHTML('beforeend','<div class="vf-modal" id="vfModal" onclick="if(event.target===this)closeModal()"><div class="vf-modal-card"><div class="vf-modal-head"><h2>'+title+'</h2><button onclick="closeModal()">×</button></div>'+body+'<div class="vf-modal-actions">'+actions+'</div></div></div>')} function closeModal(){document.getElementById('vfModal')?.remove()}
function addClient(){modal('Yeni Müşteri','<div class="form"><label>Müşteri adı<input id="mcName"></label><label>Yetkili<input id="mcContact"></label><label>Telefon<input id="mcPhone"></label><label>Sektör<select id="mcSector"><option value="emlak">Emlak</option><option value="kuyum">Kuyum</option><option value="otel">Otel</option></select></label></div>','<button class="btn" onclick="closeModal()">Vazgeç</button><button class="btn primary" onclick="saveClientModal()">Kaydet</button>')}
async function saveClientModal(){const name=val('mcName');if(!name)return alert('Müşteri adı gerekli.');const {data:{user}}=await CLOUD.auth.getUser();const {error}=await CLOUD.from('clients').insert({name,contact_person:val('mcContact'),phone:val('mcPhone'),whatsapp:val('mcPhone'),sector:val('mcSector'),status:'aktif',created_by:user.id});if(error)return cloudErr(error);await audit('Müşteri eklendi: '+name,'clients');closeModal();await refresh()}
function clientDetail(id){const c=V.data.clients.find(x=>x.id===id);if(!c)return;modal('Müşteriyi Yönet','<div class="form"><label>Ad<input id="ecName" value="'+esc(c.name)+'"></label><label>Yetkili<input id="ecContact" value="'+esc(c.contact||'')+'"></label><label>Telefon<input id="ecPhone" value="'+esc(c.phone||'')+'"></label><label>Durum<select id="ecStatus"><option value="aktif">Aktif</option><option value="pasif">Pasif</option></select></label></div>','<button class="btn danger" onclick="deleteClient(\''+id+'\')">Sil</button><button class="btn" onclick="closeModal()">Vazgeç</button><button class="btn primary" onclick="saveClientEdit(\''+id+'\')">Güncelle</button>');document.getElementById('ecStatus').value=c.status}
async function saveClientEdit(id){const {error}=await CLOUD.from('clients').update({name:val('ecName'),contact_person:val('ecContact'),phone:val('ecPhone'),whatsapp:val('ecPhone'),status:val('ecStatus')}).eq('id',id);if(error)return cloudErr(error);await audit('Müşteri güncellendi','clients',id);closeModal();await refresh()}
async function deleteClient(id){if(V.data.properties.some(x=>x.client_id===id)||V.data.jobs.some(x=>x.client_id===id))return alert('Bağlı mülk veya iş varken müşteri silinemez.');if(!confirm('Müşteri kalıcı olarak silinsin mi?'))return;const {error}=await CLOUD.from('clients').delete().eq('id',id);if(error)return cloudErr(error);closeModal();await refresh()}
function addProperty(){const e=V.data.clients.filter(x=>x.sector==='emlak');if(!e.length)return alert('Önce Emlak müşterisi ekleyin.');modal('Yeni Mülk','<div class="form"><label>Müşteri<select id="mpClient">'+e.map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join('')+'</select></label><label>Mülk adı<input id="mpName"></label><label>Adres<input id="mpAddress"></label><label>Tip<input id="mpType"></label><label>m²<input id="mpSqm" type="number"></label><label>Oda<input id="mpRooms"></label></div>','<button class="btn" onclick="closeModal()">Vazgeç</button><button class="btn primary" onclick="saveProperty()">Kaydet</button>')}
async function saveProperty(){if(!val('mpName'))return alert('Mülk adı gerekli.');const {data:{user}}=await CLOUD.auth.getUser();const {error}=await CLOUD.from('properties').insert({client_id:val('mpClient'),title:val('mpName'),address:val('mpAddress'),property_type:val('mpType'),sqm:Number(val('mpSqm')||0),rooms:val('mpRooms'),listing_status:'aktif',tour_status:'bekliyor',qr_status:'bekliyor',created_by:user.id});if(error)return cloudErr(error);await audit('Mülk eklendi','properties');closeModal();await refresh()}
function propertyDetail(id){const p=V.data.properties.find(x=>x.id===id);if(!p)return;modal('Mülkü Yönet','<div class="form"><label>Ad<input id="epName" value="'+esc(p.name)+'"></label><label>Adres<input id="epAddress" value="'+esc(p.address||'')+'"></label><label>m²<input id="epSqm" type="number" value="'+esc(p.sqm||0)+'"></label><label>360<select id="epTour"><option value="bekliyor">Bekliyor</option><option value="aktif">Aktif</option><option value="pasif">Pasif</option></select></label><label>QR<select id="epQr"><option value="bekliyor">Bekliyor</option><option value="aktif">Aktif</option><option value="pasif">Pasif</option></select></label></div>','<button class="btn" onclick="closeModal()">Vazgeç</button><button class="btn primary" onclick="savePropertyEdit(\''+id+'\')">Güncelle</button>');document.getElementById('epTour').value=p.tour_status;document.getElementById('epQr').value=p.qr_status}
async function savePropertyEdit(id){const {error}=await CLOUD.from('properties').update({title:val('epName'),address:val('epAddress'),sqm:Number(val('epSqm')||0),tour_status:val('epTour'),qr_status:val('epQr')}).eq('id',id);if(error)return cloudErr(error);await audit('Mülk güncellendi','properties',id);closeModal();await refresh()}
async function createQuote(){const cid=val('qClient'),amount=Number(val('qAmount')||0);if(!cid||amount<=0)return alert('Müşteri ve geçerli tutar gerekli.');const {data:{user}}=await CLOUD.auth.getUser();const no='VF-'+Date.now().toString().slice(-8),note=(val('qProperty')||'Proje')+' · '+val('qService');const {error}=await CLOUD.from('quotes').insert({quote_no:no,client_id:cid,sector:V.sector||'emlak',status:'taslak',currency:'TRY',subtotal:amount,total:amount,notes:note,created_by:user.id});if(error)return cloudErr(error);await audit('Teklif oluşturuldu: '+no,'quotes');await refresh()}
async function acceptQuote(id){const q=V.data.quotes.find(x=>x.id===id);if(!q)return;const {data:{user}}=await CLOUD.auth.getUser();const {error:e1}=await CLOUD.from('quotes').update({status:'kabul_edildi'}).eq('id',id);if(e1)return cloudErr(e1);const {error:e2}=await CLOUD.from('jobs').insert({client_id:q.client_id,quote_id:id,title:q.notes||q.quote_no,status:'kabul_edildi',created_by:user.id});if(e2)return cloudErr(e2);await audit('Teklif kabul edildi ve iş açıldı','quotes',id);await refresh()}
async function setJobStatus(id,status){const u={status};if(status==='teslim_edildi'||status==='odendi')u.completed_at=new Date().toISOString();const {error}=await CLOUD.from('jobs').update(u).eq('id',id);if(error)return cloudErr(error);await audit('İş durumu: '+TR[status],'jobs',id);await refresh()}
async function addTask(){const title=val('taskTitle');if(!title)return alert('Görev adı gerekli.');const {data:{user}}=await CLOUD.auth.getUser();const {error}=await CLOUD.from('tasks').insert({title,due_at:val('taskDate')||null,status:'bekliyor',priority:'normal',created_by:user.id});if(error)return cloudErr(error);await audit('Görev eklendi: '+title,'tasks');await refresh()}
async function completeTask(id){const {error}=await CLOUD.from('tasks').update({status:'tamamlandi'}).eq('id',id);if(error)return cloudErr(error);await refresh()}
function addPayment(){modal('Yeni Ödeme','<div class="form"><label>Müşteri<select id="payClient"><option value="">Seçiniz</option>'+V.data.clients.map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join('')+'</select></label><label>Tutar<input id="payAmount" type="number"></label><label>Vade<input id="payDue" type="date"></label><label>Yöntem<input id="payMethod"></label></div>','<button class="btn" onclick="closeModal()">Vazgeç</button><button class="btn primary" onclick="savePayment()">Kaydet</button>')}
async function savePayment(){const a=Number(val('payAmount')||0);if(a<=0)return alert('Geçerli tutar gerekli.');const {data:{user}}=await CLOUD.auth.getUser();const {error}=await CLOUD.from('payments').insert({client_id:val('payClient')||null,amount:a,currency:'TRY',status:'bekliyor',due_date:val('payDue')||null,payment_method:val('payMethod')||null,created_by:user.id});if(error)return cloudErr(error);closeModal();await refresh()}
async function markPayment(id){const {error}=await CLOUD.from('payments').update({status:'odendi',paid_at:new Date().toISOString()}).eq('id',id);if(error)return cloudErr(error);await refresh()}
async function healthCheck(){try{const {data:{session}}=await CLOUD.auth.getSession();if(!session)throw Error('Oturum yok');for(const t of ['clients','properties','quotes','jobs','tasks','payments']){const {error}=await CLOUD.from(t).select('id',{head:true,count:'exact'});if(error)throw error}V.cloudHealthy=true;alert('Tüm ana bağlantılar çalışıyor.');render()}catch(e){V.cloudHealthy=false;cloudErr(e);render()}}
async function backup(){await loadCloud();const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(V.data,null,2)],{type:'application/json'}));a.download='vertex-flux-'+new Date().toISOString().slice(0,10)+'.json';a.click()}
const P={
emlak:{title:'EMLAK',tag:'PORTFÖYÜ SADECE LİSTELEMEYİN, DENEYİME DÖNÜŞTÜRÜN',slides:[
{kind:'hero',kicker:'EMLAK PAZARLAMASINDA YENİ STANDART',title:'Daha fazla görünüm. Daha güçlü ilk izlenim.',text:'360° sanal tur, profesyonel Reels, drone ve akıllı QR ile portföyünüzü müşterinin karşısına daha güçlü çıkarın.',visual:'360°',points:['Portföyü 7/24 gezilebilir hale getirir','Uzaktan ön eleme sağlar','Sosyal medyada daha güçlü sunum','Tek bağlantıda düzenli müşteri deneyimi']},
{kind:'problem',kicker:'EMLAKÇININ ZAMANINI KORUR',title:'Her merak eden kişi için yeniden aynı turu yapmayın.',text:'Müşteri mülkü telefondan önceden inceler. Gerçekten ilgilenen kişi fiziksel gösterime gelir.',visual:'⌂',points:['Gereksiz gösterimleri azaltmaya yardımcı olur','Müşterinin karar öncesi daha fazla bilgi görmesini sağlar','Portföy sunumunu standartlaştırır','Ekip içinde aynı kaliteli sunumu korur']},
{kind:'qr',kicker:'AKILLI QR',title:'Tek kod. Portföyün bütün hikâyesi.',text:'Kartvizit, vitrin, ilan veya broşürdeki QR; sanal turu, videoyu, fotoğrafları ve iletişim kanalını tek mobil sayfada toplar.',visual:'QR',points:['QR hedefi değiştirilebilir','Basılı materyali yeniden bastırmadan içerik güncellenebilir','Müşteri tek dokunuşla portföye ulaşır','Daha düzenli ve profesyonel marka algısı']},
{kind:'compare',kicker:'NEDEN VERTEX FLUX?',title:'Parçalı hizmet yerine tek yönetilen deneyim.',text:'Aşağıdaki karşılaştırma hizmet kapsamını gösterir; fiyat veya sonuç garantisi değildir.',visual:'↔',rows:[['360° sanal tur','✓','Değişken','Değişken'],['Profesyonel Reels','✓','Değişken','—'],['Drone entegrasyonu','✓','Değişken','—'],['Akıllı QR sunumu','✓','Nadiren','—'],['Tek panelde yönetim','✓','Nadiren','—'],['Müşteri sunum modu','✓','Değişken','—']]},
{kind:'close',kicker:'VERTEX · EMLAK',title:'Mülkü göstermeyin. Deneyimletin.',text:'Daha düzenli portföy sunumu, daha güçlü marka algısı ve müşteriye her an ulaşabilen dijital vitrin.',visual:'V',points:['360°','REELS','DRONE','AKILLI QR']}]},
kuyum:{title:'KUYUM',tag:'MÜCEVHERİ EKRANDA DA DEĞERLİ HİSSETTİRİN',slides:[
{kind:'hero',kicker:'DİJİTAL VİTRİN',title:'Işıltıyı mağaza sınırlarının dışına taşıyın.',text:'Ürün görselleri, sinematik kısa videolar ve mobil koleksiyon sunumuyla mücevheri sosyal medyada ve müşterinin telefonunda premium gösterin.',visual:'◇',points:['Tutarlı marka görünümü','Ürüne odaklanan premium görsel dil','Reels ve kampanya içerikleri','Mobil koleksiyon sunumu']},
{kind:'problem',kicker:'DAHA HIZLI İÇERİK AKIŞI',title:'Her ürün için sıfırdan içerik düşünmek zorunda kalmayın.',text:'VERTEX, ürünleri aynı marka dili içinde görsel, video ve kampanya formatlarına dönüştüren düzenli bir sunum akışı kurar.',visual:'GEM',points:['Koleksiyonlar aynı görsel dilde ilerler','Kampanya üretimi düzenlenir','Sosyal medya formatları hazır tutulur','Mağaza ve dijital vitrin birbirini tamamlar']},
{kind:'qr',kicker:'KOLEKSİYON QR',title:'Müşteri vitrinden telefona geçsin.',text:'QR kod ile seçili koleksiyon, ürün videosu, katalog veya iletişim sayfası müşterinin telefonunda açılır.',visual:'QR',points:['Vitrin ve kartlarda kullanılabilir','Kampanyaya göre hedef değiştirilebilir','Koleksiyon paylaşımı kolaylaşır','Tek bağlantıda seçili içerikler']},
{kind:'compare',kicker:'VERTEX YAKLAŞIMI',title:'Tek tek içerik değil, bütünlüklü marka sunumu.',text:'Hizmet kapsamı karşılaştırmasıdır.',visual:'↔',rows:[['Premium ürün görseli','✓','Değişken','Değişken'],['Reels / reklam filmi','✓','Değişken','—'],['Koleksiyon QR','✓','Nadiren','—'],['Mobil dijital vitrin','✓','Değişken','—'],['Tek panelde içerik akışı','✓','Nadiren','—'],['Sektöre özel sunum','✓','Değişken','—']]},
{kind:'close',kicker:'VERTEX · KUYUM',title:'Ürünün değeri, sunumda başlar.',text:'Mağazadaki premium hissi dijitalde de koruyan, paylaşılabilir ve tutarlı bir marka deneyimi.',visual:'◇',points:['GÖRSEL','REELS','KOLEKSİYON','QR']}]},
otel:{title:'OTEL & TURİZM',tag:'MİSAFİR GELMEDEN ÖNCE DENEYİM BAŞLASIN',slides:[
{kind:'hero',kicker:'OTEL DENEYİMİ',title:'Misafire sadece oda göstermeyin. Konaklamayı hissettirin.',text:'360° tesis turu, oda sunumları, drone, Reels ve çok dilli mobil deneyim ile otelin atmosferini rezervasyon öncesinde görünür kılın.',visual:'360°',points:['Oda ve tesis alanlarını şeffaf gösterir','Uluslararası misafire mobil sunum','Sosyal medya için güçlü içerik','Tek bağlantıda tesis deneyimi']},
{kind:'problem',kicker:'REZERVASYON ÖNCESİ GÜVEN',title:'Misafir ne satın aldığını daha iyi görsün.',text:'Oda tipi, manzara, havuz, restoran ve ortak alanlar tek sunumda anlaşılır biçimde gösterilir.',visual:'HOTEL',points:['Oda tiplerini karşılaştırmayı kolaylaştırır','Tesis olanaklarını görünür kılar','Satış ekibinin aynı sunumu kullanmasını sağlar','Acente ve doğrudan müşteri paylaşımına uygundur']},
{kind:'qr',kicker:'TESİS QR',title:'Lobiden odaya, tek kodla dijital rehber.',text:'QR; tesis haritası, hizmetler, menü, etkinlik, iletişim veya seçili rezervasyon sayfasına yönlendirilebilir.',visual:'QR',points:['Oda ve ortak alanlarda kullanılabilir','İçerik sonradan güncellenebilir','Basılı materyal yükünü azaltmaya yardımcı olur','Misafirin bilgiye erişimini hızlandırır']},
{kind:'compare',kicker:'NEDEN BÜTÜNLEŞİK SUNUM?',title:'Fotoğraf galerisinden daha kapsamlı bir deneyim.',text:'Hizmet kapsamı karşılaştırmasıdır.',visual:'↔',rows:[['360° tesis turu','✓','Değişken','—'],['Oda bazlı sunum','✓','Değişken','Değişken'],['Drone / Reels','✓','Değişken','—'],['Çok dilli mobil sunum','✓','Değişken','—'],['Dinamik QR yönlendirme','✓','Nadiren','—'],['Tek panelde yönetim','✓','Nadiren','—']]},
{kind:'close',kicker:'VERTEX · OTEL',title:'Oteliniz, misafir gelmeden önce kendini anlatsın.',text:'Daha anlaşılır tesis sunumu, güçlü dijital marka algısı ve paylaşılabilir mobil deneyim.',visual:'V',points:['360°','ODA','DRONE','QR']}]}}
function presentation(type){document.getElementById('presentation')?.remove();document.body.insertAdjacentHTML('beforeend','<div class="presentation presentation-v3" id="presentation"><button class="btn close" onclick="exitPresentation()">Yöneticiye Dön</button><div id="presentationBody"></div></div>');if(type&&P[type])presentationDeck(type,0);else presentationHome()}
function presentationHome(){const b=document.getElementById('presentationBody');b.innerHTML='<div class="presentation-home"><div class="presentation-logo"><img src="'+VERTEX_LOGO+'"></div><div class="eyebrow">VERTEX DIGITAL EXPERIENCE</div><h1>Müşterinize hangi <span>hikâyeyi anlatacaksınız?</span></h1><p>Sunumu sektör seçerek başlatın. Oklarla sayfa sayfa ilerleyin.</p><div class="presentation-sector-grid">'+[['emlak','EMLAK','Portföyü deneyime dönüştür'],['kuyum','KUYUM','Işıltıyı dijitale taşı'],['otel','OTEL & TURİZM','Misafir gelmeden deneyimi başlat']].map(x=>'<button onclick="presentationDeck(\''+x[0]+'\',0)"><b>'+x[1]+'</b><small>'+x[2]+'</small><span>Sunumu başlat →</span></button>').join('')+'</div></div>'}
function deckVisual(s,type){if(s.kind==='compare')return '<div class="pitch-table"><div class="pitch-tr pitch-th"><b>Özellik / Hizmet</b><b>VERTEX</b><b>Geleneksel Ajans</b><b>Bireysel</b></div>'+s.rows.map(r=>'<div class="pitch-tr"><span>'+r[0]+'</span><strong>'+r[1]+'</strong><span>'+r[2]+'</span><span>'+r[3]+'</span></div>').join('')+'</div>';if(s.kind==='qr')return '<div class="qr-scene"><div class="qr-phone"><div class="qr-code" aria-label="QR görseli"><i></i><i></i><i></i><span></span></div><b>'+s.visual+'</b><small>'+({emlak:'PORTFÖYÜ KEŞFET',kuyum:'KOLEKSİYONU KEŞFET',otel:'TESİSİ KEŞFET'})[type]+'</small></div><div class="qr-rings"></div></div>';return '<div class="pitch-device pitch-'+type+'"><div class="pitch-orbit"></div><div class="pitch-screen"><span>'+s.visual+'</span><b>VERTEX</b><small>DIGITAL EXPERIENCE</small></div></div>'}
function presentationDeck(type,i){const d=P[type],s=d.slides[i],last=i===d.slides.length-1;document.getElementById('presentationBody').innerHTML='<div class="pitch pitch-'+type+'"><div class="pitch-top"><button class="presentation-back" onclick="'+(i?'presentationDeck(\''+type+'\','+(i-1)+')':'presentationHome()')+'"><span>‹</span> '+(i?'Geri':'Sektörler')+'</button><div class="pitch-count">0'+(i+1)+' / 0'+d.slides.length+'</div></div><div class="pitch-main"><div class="pitch-copy"><div class="eyebrow">'+s.kicker+'</div><h1>'+s.title+'</h1><p>'+s.text+'</p>'+(s.points?'<div class="pitch-points">'+s.points.map(x=>'<div><i>✓</i><span>'+x+'</span></div>').join('')+'</div>':'')+'</div><div class="pitch-media">'+deckVisual(s,type)+'</div></div><div class="pitch-bottom"><div><b>'+d.title+'</b><span>'+d.tag+'</span></div><button class="pitch-next" onclick="'+(last?'presentationHome()':'presentationDeck(\''+type+'\','+(i+1)+')')+'">'+(last?'Sunumları Bitir':'Sonraki Sayfa')+' <span>→</span></button></div></div>'}
function presentationOpen(type){presentationDeck(type,0)}
function presentationDetail(type,i){presentationDeck(type,Math.min(i,P[type].slides.length-1))}
function exitPresentation(){const p=prompt('Yönetici PIN');if(p==='2580')document.getElementById('presentation')?.remove();else if(p!==null)alert('PIN yanlış')}
async function logout(){await CLOUD.auth.signOut();login()}
function login(){document.getElementById('app').innerHTML='<div class="login"><div class="loginbox"><div class="login-logo"><img src="'+VERTEX_LOGO+'"></div><div class="eyebrow">VERTEX PRIVATE CONTROL SYSTEM</div><h1>FLUX <span>2.0</span></h1><p class="login-sub">Merkezi yönetim sistemine güvenli giriş</p><label class="pin-label">E-POSTA<input id="email" type="email" placeholder="E-posta adresiniz" autocomplete="username"></label><label class="pin-label">ŞİFRE<input id="password" type="password"></label><button class="btn primary login-button" onclick="auth()">Sisteme Gir →</button><button class="forgot-password" onclick="forgotPassword()">Şifremi Unuttum</button></div></div>'}
async function auth(){const email=val('email'),password=val('password');if(!email||!password)return alert('E-posta ve şifre gerekli.');const {error}=await CLOUD.auth.signInWithPassword({email,password});if(error)return cloudErr(error);await refresh()}
async function forgotPassword(){const email=val('email');if(!email)return alert('Şifre yenileme bağlantısı için e-posta adresinizi girin.');const {error}=await CLOUD.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(error)return cloudErr(error);alert('Şifre yenileme bağlantısı gönderildi.')}
function recoveryScreen(){document.getElementById('app').innerHTML='<div class="login"><div class="loginbox"><div class="login-logo"><img src="'+VERTEX_LOGO+'"></div><div class="eyebrow">ŞİFRE YENİLEME</div><h1>Yeni şifre</h1><label class="pin-label">YENİ ŞİFRE<input id="newPassword" type="password" minlength="8"></label><button class="btn primary login-button" onclick="setNewPassword()">Şifreyi Güncelle →</button></div></div>'}
async function setNewPassword(){const password=val('newPassword');if(password.length<8)return alert('Şifre en az 8 karakter olmalı.');const {error}=await CLOUD.auth.updateUser({password});if(error)return cloudErr(error);history.replaceState({},'',location.pathname);await refresh()}
async function refresh(){try{await loadCloud();render()}catch(e){cloudErr(e)}}
async function bootstrap(){try{if(!CLOUD)return login();CLOUD.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT')login();if(event==='PASSWORD_RECOVERY')setTimeout(recoveryScreen,0)});const {data:{session},error}=await CLOUD.auth.getSession();if(error)throw error;if(location.hash.includes('type=recovery')&&session)return recoveryScreen();if(!session)return login();await refresh()}catch(e){console.error('VERTEX bootstrap error',e);login()}}
bootstrap();,health:'◆',admin:'⚙'};
function nav(){return [['dashboard','Panel'],['quotes','Teklifler'],['jobs','İşler'],['calendar','Takvim / Görevler'],['clients','Müşteriler'],['properties','Mülkler'],['market','Piyasa'],['gallery','Örnek Galeri'],['costs','Finans Merkezi'],['health','Sistem Sağlığı'],['admin','Uzaktan Yönetim']].map(([k,t])=>'<button class="'+(V.screen===k?'active':'')+'" onclick="go(\''+k+'\')"><span class="ni">'+icons[k]+'</span><span>'+t+'</span></button>').join('')}
function layout(body,title,sub='VERTEX SUPER ADMIN'){const back=V.screen!=='dashboard'?'<button class="back-btn" onclick="goBack()" aria-label="Geri dön"><span>←</span> Geri</button>':'';return '<div class="shell"><aside class="side"><div class="brand"><div class="brand-mark"><img src="'+VERTEX_LOGO+'"></div><div><b>VERTEX</b><small>FLUX 2.0</small></div></div><div class="nav">'+nav()+'<div class="sep"></div><button onclick="presentation()">▣ <span>Müşteri Sunumu</span></button><button onclick="logout()">⇥ <span>Kilitle</span></button></div></aside><main class="main">'+back+'<div class="top"><div><div class="eyebrow">'+sub+'</div><h1>'+title+'</h1></div><div class="actions"><button class="btn" onclick="backup()">Yedek Al</button><button class="btn primary" onclick="newQuote()">+ Yeni Teklif</button></div></div>'+body+'</main></div>'}
function sectorCards(){const a=[['emlak','EMLAK','360° Portföy Yönetimi','Mülk · 360° Tur · QR · Portföy'],['kuyum','KUYUM','Premium Ürün Deneyimi','Mücevher · Görsel · Video · Dijital Mağaza'],['otel','OTEL & TURİZM','Mekân Deneyimi','Tesis · Oda · 360° · Drone · QR']];return '<div class="sector-grid">'+a.map((c,i)=>'<button class="sector-card sector-'+c[0]+'" onclick="openSectorWorkspace(\''+c[0]+'\')"><div class="sector-visual"><div class="sector-art">'+VERTEX_SECTOR_ART[c[0]]+'</div><span class="sector-number">0'+(i+1)+'</span></div><div class="sector-copy"><span class="sector-kicker">'+c[2]+'</span><h3>'+c[1]+'</h3><p>'+c[3]+'</p><span class="sector-enter">ÇALIŞMA ALANINA GİR →</span></div></button>').join('')+'</div>'}
function dashboard(){const d=V.data;return layout('<div class="dashboard-hero"><h2>VERTEX <span>Kontrol Merkezi</span></h2><p>Üç sektörün operasyonunu tek merkezden yönetin.</p></div><div class="grid stats"><div class="card stat"><span>Müşteri</span><strong>'+d.clients.length+'</strong></div><div class="card stat"><span>İş</span><strong>'+d.jobs.length+'</strong></div><div class="card stat"><span>Mülk</span><strong>'+d.properties.length+'</strong></div><div class="card stat"><span>Bulut</span><strong class="'+(V.cloudHealthy?'ok':'warn')+'">'+(V.cloudHealthy?'Bağlı':'Kontrol')+'</strong></div></div>'+sectorCards(),'Kontrol Merkezi')}
function goBack(){if(V.screen==='sectorWorkspace'){V.screen='dashboard';render();return}if(['clients','properties','quotes','jobs','calendar','costs','market','gallery','health','admin'].includes(V.screen)){V.screen='sectorWorkspace';render();return}V.screen='dashboard';render()}
function openSectorWorkspace(s){V.sector=s;V.screen='sectorWorkspace';render()}
function sectorWorkspace(){const cfg={emlak:['EMLAK ÇALIŞMA ALANI','360° PORTFÖY YÖNETİMİ',[['Müşteriler','clients'],['Mülkler','properties'],['Teklifler','quotes'],['İşler','jobs'],['Takvim','calendar'],['Finans','costs']]],kuyum:['KUYUM ÇALIŞMA ALANI','PREMİUM ÜRÜN DENEYİMİ',[['Müşteriler','clients'],['Ürün Görselleri','gallery'],['Reklam Filmleri','gallery'],['Teklifler','quotes'],['Takvim','calendar'],['Müşteri Sunumu','presentation']]],otel:['OTEL & TURİZM ÇALIŞMA ALANI','MEKÂN DENEYİMİ',[['Müşteriler','clients'],['360° Tesis Turu','presentation'],['Drone','presentation'],['Teklifler','quotes'],['Takvim','calendar'],['Müşteri Sunumu','presentation']]]};const d=cfg[V.sector];return layout('<div class="workspace-hero workspace-'+V.sector+'"><div class="eyebrow">'+d[1]+'</div><h2>'+d[0]+'</h2><p>Bu sektöre ait müşteri, içerik, teklif ve operasyon araçları.</p><button class="btn" onclick="go(\'dashboard\')">← Kontrol Merkezine Dön</button></div><div class="workspace-grid">'+d[2].map((a,i)=>'<button class="workspace-action" onclick="'+(a[1]==='presentation'?'presentation(\''+V.sector+'\')':'go(\''+a[1]+'\')')+'"><span>0'+(i+1)+'</span><div><b>'+a[0]+'</b><small>Aç ve yönet</small></div><i>→</i></button>').join('')+'</div>',d[0],d[1])}
function clients(){const rows=V.data.clients.filter(x=>V.sector==='emlak'?x.sector==='emlak':true).map(c=>'<div class="row"><b>'+esc(c.name)+'</b><span>'+esc((c.sector||'').toUpperCase())+'</span><span class="ok">● '+esc(TR[c.status]||c.status)+'</span><button class="btn" onclick="clientDetail(\''+c.id+'\')">Aç</button></div>').join('');return layout('<div class="card"><div class="section-title"><h2>Müşteriler</h2><button class="btn primary" onclick="addClient()">+ Müşteri Ekle</button></div><div class="list">'+(rows||'<div class="empty-state">Henüz müşteri yok.</div>')+'</div></div>','Müşteriler')}
function properties(){const rows=V.data.properties.map(p=>'<div class="row"><b>'+esc(p.name)+'<br><small class="muted">'+esc(p.client)+'</small></b><span>'+esc(p.sqm||0)+' m²</span><span>360: '+esc(p.tour)+' · QR: '+esc(p.qr)+'</span><button class="btn" onclick="propertyDetail(\''+p.id+'\')">Yönet</button></div>').join('');return layout('<div class="card"><div class="section-title"><h2>Emlak Mülkleri</h2><button class="btn primary" onclick="addProperty()">+ Mülk Ekle</button></div><div class="list">'+(rows||'<div class="empty-state">Henüz mülk yok.</div>')+'</div></div>','Mülkler','EMLAK · PORTFÖY')}
function quotes(){const rows=V.data.quotes.map(q=>'<div class="row"><b>'+esc(q.quote_no||q.property)+'</b><span>'+esc(q.client)+'</span><span>'+Number(q.total||q.amount||0).toLocaleString('tr-TR')+' ₺</span><button class="btn" '+(q.status==='kabul_edildi'?'disabled':'onclick="acceptQuote(\''+q.id+'\')"')+'>'+(q.status==='kabul_edildi'?'Kabul edildi':'Kabul Et')+'</button></div>').join('');return layout('<div class="grid cols"><div class="card"><h2>Yeni Teklif</h2><div class="form"><label>Müşteri<select id="qClient">'+V.data.clients.map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join('')+'</select></label><label>Mülk / Proje<input id="qProperty"></label><label>Hizmet<select id="qService"><option>360° Sanal Tur</option><option>Drone</option><option>Reels</option><option>360° + Drone + Reels</option></select></label><label>Tutar (TL)<input id="qAmount" type="number" min="0"></label></div><button class="btn primary" onclick="createQuote()">Teklifi Kaydet</button></div><div class="card"><h2>Kayıtlı Teklifler</h2>'+(rows||'<div class="empty-state">Henüz teklif yok.</div>')+'</div></div>','Teklifler')}
function jobs(){const steps=['kabul_edildi','planlandi','cekildi','duzenleniyor','musteri_onayi','teslim_edildi','odeme_bekliyor','odendi'];const rows=V.data.jobs.map(j=>'<div class="card"><div class="section-title"><h2>'+esc(j.title)+'</h2><span class="pill">'+esc(j.client)+'</span></div><p class="muted">'+esc(j.date)+'</p><div class="timeline">'+steps.map(s=>'<button class="step '+(j.status===s?'done':'')+'" onclick="setJobStatus(\''+j.id+'\',\''+s+'\')">'+TR[s]+'</button>').join('')+'</div></div>').join('');return layout('<div class="list">'+(rows||'<div class="empty-state">Henüz iş yok.</div>')+'</div>','İşler','TEKLİFTEN TESLİMATA')}
function calendar(){const rows=V.data.tasks.map(t=>'<div class="row"><b>'+esc(t.date)+'</b><span>'+esc(t.title)+'</span><span class="pill">'+esc(TR[t.status]||t.status)+'</span><button class="btn" onclick="completeTask(\''+t.id+'\')">Tamamla</button></div>').join('');return layout('<div class="grid cols"><div class="card"><h2>Takvim</h2>'+(rows||'<div class="empty-state">Görev yok.</div>')+'</div><div class="card"><h2>Yeni Görev</h2><div class="form"><label>Görev<input id="taskTitle"></label><label>Tarih<input id="taskDate" type="datetime-local"></label></div><button class="btn primary" onclick="addTask()">Görev Ekle</button></div></div>','Takvim / Görevler')}
function costs(){const p=V.data.payments,paid=p.filter(x=>x.status==='odendi').reduce((a,x)=>a+Number(x.amount||0),0),pending=p.filter(x=>x.status!=='odendi').reduce((a,x)=>a+Number(x.amount||0),0);return layout('<div class="grid stats"><div class="card stat"><span>Tahsil</span><strong>'+paid.toLocaleString('tr-TR')+' ₺</strong></div><div class="card stat"><span>Bekleyen</span><strong>'+pending.toLocaleString('tr-TR')+' ₺</strong></div></div><div class="card"><div class="section-title"><h2>Ödemeler</h2><button class="btn primary" onclick="addPayment()">+ Ödeme Ekle</button></div>'+p.map(x=>'<div class="row"><b>'+Number(x.amount).toLocaleString('tr-TR')+' ₺</b><span>'+esc(TR[x.status]||x.status)+'</span><span>'+esc(x.due_date||'—')+'</span><button class="btn" '+(x.status==='odendi'?'disabled':'onclick="markPayment(\''+x.id+'\')"')+'>Ödendi</button></div>').join('')+'</div>','Finans Merkezi','GİZLİ · SUPER ADMIN')}
function market(){return layout('<div class="card"><h2>Piyasa Araştırması</h2><p class="muted">Doğrulanmış güncel veri eklenmeden sistem fiyat veya rakip bilgisi üretmez.</p></div>','Piyasa','SADECE SUPER ADMIN')}
function gallery(){return layout('<div class="card"><h2>Müşteri Sunum Galerisi</h2><p class="muted">Emlak, Kuyum ve Otel hizmetlerini tam ekran müşteri sunumunda inceleyin.</p><button class="btn primary" onclick="presentation(\''+V.sector+'\')">Sunumu Aç</button></div>','Örnek Galeri')}
function health(){return layout('<div class="card"><div class="section-title"><h2>Canlı Bağlantı Kontrolü</h2><button class="btn primary" onclick="healthCheck()">Şimdi Kontrol Et</button></div><p class="muted">Oturum ve tüm ana veri tabloları test edilir.</p><div class="notice">'+(V.cloudHealthy?'Supabase bağlantısı son yüklemede başarılı.':'Kontrol bekleniyor.')+'</div></div>','Sistem Sağlığı')}
function admin(){return layout('<div class="grid cols"><div class="card"><h2>Bulut Yönetimi</h2><p class="muted">Supabase Auth, RLS ve merkezi veri katmanı aktif.</p><button class="btn primary" onclick="healthCheck()">Bağlantıları Test Et</button></div><div class="card"><h2>İşlem Geçmişi</h2>'+V.data.audit.slice(0,12).map(a=>'<div><small class="muted">'+esc(a.at)+'</small><br>'+esc(a.action)+'</div>').join('')+'</div></div>','Uzaktan Yönetim','SUPER ADMIN')}
function go(s){V.screen=s;render()} function newQuote(){go('quotes')}
function render(){const f={dashboard,sectorWorkspace,clients,properties,quotes,jobs,calendar,costs,market,gallery,health,admin};document.getElementById('app').innerHTML=(f[V.screen]||dashboard)()}
function modal(title,body,actions=''){document.getElementById('vfModal')?.remove();document.body.insertAdjacentHTML('beforeend','<div class="vf-modal" id="vfModal" onclick="if(event.target===this)closeModal()"><div class="vf-modal-card"><div class="vf-modal-head"><h2>'+title+'</h2><button onclick="closeModal()">×</button></div>'+body+'<div class="vf-modal-actions">'+actions+'</div></div></div>')} function closeModal(){document.getElementById('vfModal')?.remove()}
function addClient(){modal('Yeni Müşteri','<div class="form"><label>Müşteri adı<input id="mcName"></label><label>Yetkili<input id="mcContact"></label><label>Telefon<input id="mcPhone"></label><label>Sektör<select id="mcSector"><option value="emlak">Emlak</option><option value="kuyum">Kuyum</option><option value="otel">Otel</option></select></label></div>','<button class="btn" onclick="closeModal()">Vazgeç</button><button class="btn primary" onclick="saveClientModal()">Kaydet</button>')}
async function saveClientModal(){const name=val('mcName');if(!name)return alert('Müşteri adı gerekli.');const {data:{user}}=await CLOUD.auth.getUser();const {error}=await CLOUD.from('clients').insert({name,contact_person:val('mcContact'),phone:val('mcPhone'),whatsapp:val('mcPhone'),sector:val('mcSector'),status:'aktif',created_by:user.id});if(error)return cloudErr(error);await audit('Müşteri eklendi: '+name,'clients');closeModal();await refresh()}
function clientDetail(id){const c=V.data.clients.find(x=>x.id===id);if(!c)return;modal('Müşteriyi Yönet','<div class="form"><label>Ad<input id="ecName" value="'+esc(c.name)+'"></label><label>Yetkili<input id="ecContact" value="'+esc(c.contact||'')+'"></label><label>Telefon<input id="ecPhone" value="'+esc(c.phone||'')+'"></label><label>Durum<select id="ecStatus"><option value="aktif">Aktif</option><option value="pasif">Pasif</option></select></label></div>','<button class="btn danger" onclick="deleteClient(\''+id+'\')">Sil</button><button class="btn" onclick="closeModal()">Vazgeç</button><button class="btn primary" onclick="saveClientEdit(\''+id+'\')">Güncelle</button>');document.getElementById('ecStatus').value=c.status}
async function saveClientEdit(id){const {error}=await CLOUD.from('clients').update({name:val('ecName'),contact_person:val('ecContact'),phone:val('ecPhone'),whatsapp:val('ecPhone'),status:val('ecStatus')}).eq('id',id);if(error)return cloudErr(error);await audit('Müşteri güncellendi','clients',id);closeModal();await refresh()}
async function deleteClient(id){if(V.data.properties.some(x=>x.client_id===id)||V.data.jobs.some(x=>x.client_id===id))return alert('Bağlı mülk veya iş varken müşteri silinemez.');if(!confirm('Müşteri kalıcı olarak silinsin mi?'))return;const {error}=await CLOUD.from('clients').delete().eq('id',id);if(error)return cloudErr(error);closeModal();await refresh()}
function addProperty(){const e=V.data.clients.filter(x=>x.sector==='emlak');if(!e.length)return alert('Önce Emlak müşterisi ekleyin.');modal('Yeni Mülk','<div class="form"><label>Müşteri<select id="mpClient">'+e.map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join('')+'</select></label><label>Mülk adı<input id="mpName"></label><label>Adres<input id="mpAddress"></label><label>Tip<input id="mpType"></label><label>m²<input id="mpSqm" type="number"></label><label>Oda<input id="mpRooms"></label></div>','<button class="btn" onclick="closeModal()">Vazgeç</button><button class="btn primary" onclick="saveProperty()">Kaydet</button>')}
async function saveProperty(){if(!val('mpName'))return alert('Mülk adı gerekli.');const {data:{user}}=await CLOUD.auth.getUser();const {error}=await CLOUD.from('properties').insert({client_id:val('mpClient'),title:val('mpName'),address:val('mpAddress'),property_type:val('mpType'),sqm:Number(val('mpSqm')||0),rooms:val('mpRooms'),listing_status:'aktif',tour_status:'bekliyor',qr_status:'bekliyor',created_by:user.id});if(error)return cloudErr(error);await audit('Mülk eklendi','properties');closeModal();await refresh()}
function propertyDetail(id){const p=V.data.properties.find(x=>x.id===id);if(!p)return;modal('Mülkü Yönet','<div class="form"><label>Ad<input id="epName" value="'+esc(p.name)+'"></label><label>Adres<input id="epAddress" value="'+esc(p.address||'')+'"></label><label>m²<input id="epSqm" type="number" value="'+esc(p.sqm||0)+'"></label><label>360<select id="epTour"><option value="bekliyor">Bekliyor</option><option value="aktif">Aktif</option><option value="pasif">Pasif</option></select></label><label>QR<select id="epQr"><option value="bekliyor">Bekliyor</option><option value="aktif">Aktif</option><option value="pasif">Pasif</option></select></label></div>','<button class="btn" onclick="closeModal()">Vazgeç</button><button class="btn primary" onclick="savePropertyEdit(\''+id+'\')">Güncelle</button>');document.getElementById('epTour').value=p.tour_status;document.getElementById('epQr').value=p.qr_status}
async function savePropertyEdit(id){const {error}=await CLOUD.from('properties').update({title:val('epName'),address:val('epAddress'),sqm:Number(val('epSqm')||0),tour_status:val('epTour'),qr_status:val('epQr')}).eq('id',id);if(error)return cloudErr(error);await audit('Mülk güncellendi','properties',id);closeModal();await refresh()}
async function createQuote(){const cid=val('qClient'),amount=Number(val('qAmount')||0);if(!cid||amount<=0)return alert('Müşteri ve geçerli tutar gerekli.');const {data:{user}}=await CLOUD.auth.getUser();const no='VF-'+Date.now().toString().slice(-8),note=(val('qProperty')||'Proje')+' · '+val('qService');const {error}=await CLOUD.from('quotes').insert({quote_no:no,client_id:cid,sector:V.sector||'emlak',status:'taslak',currency:'TRY',subtotal:amount,total:amount,notes:note,created_by:user.id});if(error)return cloudErr(error);await audit('Teklif oluşturuldu: '+no,'quotes');await refresh()}
async function acceptQuote(id){const q=V.data.quotes.find(x=>x.id===id);if(!q)return;const {data:{user}}=await CLOUD.auth.getUser();const {error:e1}=await CLOUD.from('quotes').update({status:'kabul_edildi'}).eq('id',id);if(e1)return cloudErr(e1);const {error:e2}=await CLOUD.from('jobs').insert({client_id:q.client_id,quote_id:id,title:q.notes||q.quote_no,status:'kabul_edildi',created_by:user.id});if(e2)return cloudErr(e2);await audit('Teklif kabul edildi ve iş açıldı','quotes',id);await refresh()}
async function setJobStatus(id,status){const u={status};if(status==='teslim_edildi'||status==='odendi')u.completed_at=new Date().toISOString();const {error}=await CLOUD.from('jobs').update(u).eq('id',id);if(error)return cloudErr(error);await audit('İş durumu: '+TR[status],'jobs',id);await refresh()}
async function addTask(){const title=val('taskTitle');if(!title)return alert('Görev adı gerekli.');const {data:{user}}=await CLOUD.auth.getUser();const {error}=await CLOUD.from('tasks').insert({title,due_at:val('taskDate')||null,status:'bekliyor',priority:'normal',created_by:user.id});if(error)return cloudErr(error);await audit('Görev eklendi: '+title,'tasks');await refresh()}
async function completeTask(id){const {error}=await CLOUD.from('tasks').update({status:'tamamlandi'}).eq('id',id);if(error)return cloudErr(error);await refresh()}
function addPayment(){modal('Yeni Ödeme','<div class="form"><label>Müşteri<select id="payClient"><option value="">Seçiniz</option>'+V.data.clients.map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join('')+'</select></label><label>Tutar<input id="payAmount" type="number"></label><label>Vade<input id="payDue" type="date"></label><label>Yöntem<input id="payMethod"></label></div>','<button class="btn" onclick="closeModal()">Vazgeç</button><button class="btn primary" onclick="savePayment()">Kaydet</button>')}
async function savePayment(){const a=Number(val('payAmount')||0);if(a<=0)return alert('Geçerli tutar gerekli.');const {data:{user}}=await CLOUD.auth.getUser();const {error}=await CLOUD.from('payments').insert({client_id:val('payClient')||null,amount:a,currency:'TRY',status:'bekliyor',due_date:val('payDue')||null,payment_method:val('payMethod')||null,created_by:user.id});if(error)return cloudErr(error);closeModal();await refresh()}
async function markPayment(id){const {error}=await CLOUD.from('payments').update({status:'odendi',paid_at:new Date().toISOString()}).eq('id',id);if(error)return cloudErr(error);await refresh()}
async function healthCheck(){try{const {data:{session}}=await CLOUD.auth.getSession();if(!session)throw Error('Oturum yok');for(const t of ['clients','properties','quotes','jobs','tasks','payments']){const {error}=await CLOUD.from(t).select('id',{head:true,count:'exact'});if(error)throw error}V.cloudHealthy=true;alert('Tüm ana bağlantılar çalışıyor.');render()}catch(e){V.cloudHealthy=false;cloudErr(e);render()}}
async function backup(){await loadCloud();const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(V.data,null,2)],{type:'application/json'}));a.download='vertex-flux-'+new Date().toISOString().slice(0,10)+'.json';a.click()}
const P={
emlak:{title:'EMLAK',tag:'PORTFÖYÜ SADECE LİSTELEMEYİN, DENEYİME DÖNÜŞTÜRÜN',slides:[
{kind:'hero',kicker:'EMLAK PAZARLAMASINDA YENİ STANDART',title:'Daha fazla görünüm. Daha güçlü ilk izlenim.',text:'360° sanal tur, profesyonel Reels, drone ve akıllı QR ile portföyünüzü müşterinin karşısına daha güçlü çıkarın.',visual:'360°',points:['Portföyü 7/24 gezilebilir hale getirir','Uzaktan ön eleme sağlar','Sosyal medyada daha güçlü sunum','Tek bağlantıda düzenli müşteri deneyimi']},
{kind:'problem',kicker:'EMLAKÇININ ZAMANINI KORUR',title:'Her merak eden kişi için yeniden aynı turu yapmayın.',text:'Müşteri mülkü telefondan önceden inceler. Gerçekten ilgilenen kişi fiziksel gösterime gelir.',visual:'⌂',points:['Gereksiz gösterimleri azaltmaya yardımcı olur','Müşterinin karar öncesi daha fazla bilgi görmesini sağlar','Portföy sunumunu standartlaştırır','Ekip içinde aynı kaliteli sunumu korur']},
{kind:'qr',kicker:'AKILLI QR',title:'Tek kod. Portföyün bütün hikâyesi.',text:'Kartvizit, vitrin, ilan veya broşürdeki QR; sanal turu, videoyu, fotoğrafları ve iletişim kanalını tek mobil sayfada toplar.',visual:'QR',points:['QR hedefi değiştirilebilir','Basılı materyali yeniden bastırmadan içerik güncellenebilir','Müşteri tek dokunuşla portföye ulaşır','Daha düzenli ve profesyonel marka algısı']},
{kind:'compare',kicker:'NEDEN VERTEX FLUX?',title:'Parçalı hizmet yerine tek yönetilen deneyim.',text:'Aşağıdaki karşılaştırma hizmet kapsamını gösterir; fiyat veya sonuç garantisi değildir.',visual:'↔',rows:[['360° sanal tur','✓','Değişken','Değişken'],['Profesyonel Reels','✓','Değişken','—'],['Drone entegrasyonu','✓','Değişken','—'],['Akıllı QR sunumu','✓','Nadiren','—'],['Tek panelde yönetim','✓','Nadiren','—'],['Müşteri sunum modu','✓','Değişken','—']]},
{kind:'close',kicker:'VERTEX · EMLAK',title:'Mülkü göstermeyin. Deneyimletin.',text:'Daha düzenli portföy sunumu, daha güçlü marka algısı ve müşteriye her an ulaşabilen dijital vitrin.',visual:'V',points:['360°','REELS','DRONE','AKILLI QR']}]},
kuyum:{title:'KUYUM',tag:'MÜCEVHERİ EKRANDA DA DEĞERLİ HİSSETTİRİN',slides:[
{kind:'hero',kicker:'DİJİTAL VİTRİN',title:'Işıltıyı mağaza sınırlarının dışına taşıyın.',text:'Ürün görselleri, sinematik kısa videolar ve mobil koleksiyon sunumuyla mücevheri sosyal medyada ve müşterinin telefonunda premium gösterin.',visual:'◇',points:['Tutarlı marka görünümü','Ürüne odaklanan premium görsel dil','Reels ve kampanya içerikleri','Mobil koleksiyon sunumu']},
{kind:'problem',kicker:'DAHA HIZLI İÇERİK AKIŞI',title:'Her ürün için sıfırdan içerik düşünmek zorunda kalmayın.',text:'VERTEX, ürünleri aynı marka dili içinde görsel, video ve kampanya formatlarına dönüştüren düzenli bir sunum akışı kurar.',visual:'GEM',points:['Koleksiyonlar aynı görsel dilde ilerler','Kampanya üretimi düzenlenir','Sosyal medya formatları hazır tutulur','Mağaza ve dijital vitrin birbirini tamamlar']},
{kind:'qr',kicker:'KOLEKSİYON QR',title:'Müşteri vitrinden telefona geçsin.',text:'QR kod ile seçili koleksiyon, ürün videosu, katalog veya iletişim sayfası müşterinin telefonunda açılır.',visual:'QR',points:['Vitrin ve kartlarda kullanılabilir','Kampanyaya göre hedef değiştirilebilir','Koleksiyon paylaşımı kolaylaşır','Tek bağlantıda seçili içerikler']},
{kind:'compare',kicker:'VERTEX YAKLAŞIMI',title:'Tek tek içerik değil, bütünlüklü marka sunumu.',text:'Hizmet kapsamı karşılaştırmasıdır.',visual:'↔',rows:[['Premium ürün görseli','✓','Değişken','Değişken'],['Reels / reklam filmi','✓','Değişken','—'],['Koleksiyon QR','✓','Nadiren','—'],['Mobil dijital vitrin','✓','Değişken','—'],['Tek panelde içerik akışı','✓','Nadiren','—'],['Sektöre özel sunum','✓','Değişken','—']]},
{kind:'close',kicker:'VERTEX · KUYUM',title:'Ürünün değeri, sunumda başlar.',text:'Mağazadaki premium hissi dijitalde de koruyan, paylaşılabilir ve tutarlı bir marka deneyimi.',visual:'◇',points:['GÖRSEL','REELS','KOLEKSİYON','QR']}]},
otel:{title:'OTEL & TURİZM',tag:'MİSAFİR GELMEDEN ÖNCE DENEYİM BAŞLASIN',slides:[
{kind:'hero',kicker:'OTEL DENEYİMİ',title:'Misafire sadece oda göstermeyin. Konaklamayı hissettirin.',text:'360° tesis turu, oda sunumları, drone, Reels ve çok dilli mobil deneyim ile otelin atmosferini rezervasyon öncesinde görünür kılın.',visual:'360°',points:['Oda ve tesis alanlarını şeffaf gösterir','Uluslararası misafire mobil sunum','Sosyal medya için güçlü içerik','Tek bağlantıda tesis deneyimi']},
{kind:'problem',kicker:'REZERVASYON ÖNCESİ GÜVEN',title:'Misafir ne satın aldığını daha iyi görsün.',text:'Oda tipi, manzara, havuz, restoran ve ortak alanlar tek sunumda anlaşılır biçimde gösterilir.',visual:'HOTEL',points:['Oda tiplerini karşılaştırmayı kolaylaştırır','Tesis olanaklarını görünür kılar','Satış ekibinin aynı sunumu kullanmasını sağlar','Acente ve doğrudan müşteri paylaşımına uygundur']},
{kind:'qr',kicker:'TESİS QR',title:'Lobiden odaya, tek kodla dijital rehber.',text:'QR; tesis haritası, hizmetler, menü, etkinlik, iletişim veya seçili rezervasyon sayfasına yönlendirilebilir.',visual:'QR',points:['Oda ve ortak alanlarda kullanılabilir','İçerik sonradan güncellenebilir','Basılı materyal yükünü azaltmaya yardımcı olur','Misafirin bilgiye erişimini hızlandırır']},
{kind:'compare',kicker:'NEDEN BÜTÜNLEŞİK SUNUM?',title:'Fotoğraf galerisinden daha kapsamlı bir deneyim.',text:'Hizmet kapsamı karşılaştırmasıdır.',visual:'↔',rows:[['360° tesis turu','✓','Değişken','—'],['Oda bazlı sunum','✓','Değişken','Değişken'],['Drone / Reels','✓','Değişken','—'],['Çok dilli mobil sunum','✓','Değişken','—'],['Dinamik QR yönlendirme','✓','Nadiren','—'],['Tek panelde yönetim','✓','Nadiren','—']]},
{kind:'close',kicker:'VERTEX · OTEL',title:'Oteliniz, misafir gelmeden önce kendini anlatsın.',text:'Daha anlaşılır tesis sunumu, güçlü dijital marka algısı ve paylaşılabilir mobil deneyim.',visual:'V',points:['360°','ODA','DRONE','QR']}]}}
function presentation(type){document.getElementById('presentation')?.remove();document.body.insertAdjacentHTML('beforeend','<div class="presentation presentation-v3" id="presentation"><button class="btn close" onclick="exitPresentation()">Yöneticiye Dön</button><div id="presentationBody"></div></div>');if(type&&P[type])presentationDeck(type,0);else presentationHome()}
function presentationHome(){const b=document.getElementById('presentationBody');b.innerHTML='<div class="presentation-home"><div class="presentation-logo"><img src="'+VERTEX_LOGO+'"></div><div class="eyebrow">VERTEX DIGITAL EXPERIENCE</div><h1>Müşterinize hangi <span>hikâyeyi anlatacaksınız?</span></h1><p>Sunumu sektör seçerek başlatın. Oklarla sayfa sayfa ilerleyin.</p><div class="presentation-sector-grid">'+[['emlak','EMLAK','Portföyü deneyime dönüştür'],['kuyum','KUYUM','Işıltıyı dijitale taşı'],['otel','OTEL & TURİZM','Misafir gelmeden deneyimi başlat']].map(x=>'<button onclick="presentationDeck(\''+x[0]+'\',0)"><b>'+x[1]+'</b><small>'+x[2]+'</small><span>Sunumu başlat →</span></button>').join('')+'</div></div>'}
function deckVisual(s,type){if(s.kind==='compare')return '<div class="pitch-table"><div class="pitch-tr pitch-th"><b>Özellik / Hizmet</b><b>VERTEX</b><b>Geleneksel Ajans</b><b>Bireysel</b></div>'+s.rows.map(r=>'<div class="pitch-tr"><span>'+r[0]+'</span><strong>'+r[1]+'</strong><span>'+r[2]+'</span><span>'+r[3]+'</span></div>').join('')+'</div>';if(s.kind==='qr')return '<div class="qr-scene"><div class="qr-phone"><div class="qr-code" aria-label="QR görseli"><i></i><i></i><i></i><span></span></div><b>'+s.visual+'</b><small>'+({emlak:'PORTFÖYÜ KEŞFET',kuyum:'KOLEKSİYONU KEŞFET',otel:'TESİSİ KEŞFET'})[type]+'</small></div><div class="qr-rings"></div></div>';return '<div class="pitch-device pitch-'+type+'"><div class="pitch-orbit"></div><div class="pitch-screen"><span>'+s.visual+'</span><b>VERTEX</b><small>DIGITAL EXPERIENCE</small></div></div>'}
function presentationDeck(type,i){const d=P[type],s=d.slides[i],last=i===d.slides.length-1;document.getElementById('presentationBody').innerHTML='<div class="pitch pitch-'+type+'"><div class="pitch-top"><button class="presentation-back" onclick="'+(i?'presentationDeck(\''+type+'\','+(i-1)+')':'presentationHome()')+'"><span>‹</span> '+(i?'Geri':'Sektörler')+'</button><div class="pitch-count">0'+(i+1)+' / 0'+d.slides.length+'</div></div><div class="pitch-main"><div class="pitch-copy"><div class="eyebrow">'+s.kicker+'</div><h1>'+s.title+'</h1><p>'+s.text+'</p>'+(s.points?'<div class="pitch-points">'+s.points.map(x=>'<div><i>✓</i><span>'+x+'</span></div>').join('')+'</div>':'')+'</div><div class="pitch-media">'+deckVisual(s,type)+'</div></div><div class="pitch-bottom"><div><b>'+d.title+'</b><span>'+d.tag+'</span></div><button class="pitch-next" onclick="'+(last?'presentationHome()':'presentationDeck(\''+type+'\','+(i+1)+')')+'">'+(last?'Sunumları Bitir':'Sonraki Sayfa')+' <span>→</span></button></div></div>'}
function presentationOpen(type){presentationDeck(type,0)}
function presentationDetail(type,i){presentationDeck(type,Math.min(i,P[type].slides.length-1))}
function exitPresentation(){const p=prompt('Yönetici PIN');if(p==='2580')document.getElementById('presentation')?.remove();else if(p!==null)alert('PIN yanlış')}
async function logout(){await CLOUD.auth.signOut();login()}
function login(){document.getElementById('app').innerHTML='<div class="login"><div class="loginbox"><div class="login-logo"><img src="'+VERTEX_LOGO+'"></div><div class="eyebrow">VERTEX PRIVATE CONTROL SYSTEM</div><h1>FLUX <span>2.0</span></h1><p class="login-sub">Merkezi yönetim sistemine güvenli giriş</p><label class="pin-label">E-POSTA<input id="email" type="email" placeholder="E-posta adresiniz" autocomplete="username"></label><label class="pin-label">ŞİFRE<input id="password" type="password"></label><button class="btn primary login-button" onclick="auth()">Sisteme Gir →</button><button class="forgot-password" onclick="forgotPassword()">Şifremi Unuttum</button></div></div>'}
async function auth(){const email=val('email'),password=val('password');if(!email||!password)return alert('E-posta ve şifre gerekli.');const {error}=await CLOUD.auth.signInWithPassword({email,password});if(error)return cloudErr(error);await refresh()}
async function forgotPassword(){const email=val('email');if(!email)return alert('Şifre yenileme bağlantısı için e-posta adresinizi girin.');const {error}=await CLOUD.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(error)return cloudErr(error);alert('Şifre yenileme bağlantısı gönderildi.')}
function recoveryScreen(){document.getElementById('app').innerHTML='<div class="login"><div class="loginbox"><div class="login-logo"><img src="'+VERTEX_LOGO+'"></div><div class="eyebrow">ŞİFRE YENİLEME</div><h1>Yeni şifre</h1><label class="pin-label">YENİ ŞİFRE<input id="newPassword" type="password" minlength="8"></label><button class="btn primary login-button" onclick="setNewPassword()">Şifreyi Güncelle →</button></div></div>'}
async function setNewPassword(){const password=val('newPassword');if(password.length<8)return alert('Şifre en az 8 karakter olmalı.');const {error}=await CLOUD.auth.updateUser({password});if(error)return cloudErr(error);history.replaceState({},'',location.pathname);await refresh()}
async function refresh(){try{await loadCloud();render()}catch(e){cloudErr(e)}}
async function bootstrap(){try{if(!CLOUD)return login();CLOUD.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT')login();if(event==='PASSWORD_RECOVERY')setTimeout(recoveryScreen,0)});const {data:{session},error}=await CLOUD.auth.getSession();if(error)throw error;if(location.hash.includes('type=recovery')&&session)return recoveryScreen();if(!session)return login();await refresh()}catch(e){console.error('VERTEX bootstrap error',e);login()}}
bootstrap();