/* Kuyumcu vitrini: source photos stay private; only explicitly approved images reach the public collection. */
const JEWELRY_CATEGORIES={yuzuk:'Yüzük',kupe:'Küpe',kolye:'Kolye',bilezik:'Bilezik',diger:'Diğer'};
function jewelryStudio(){
 const shops=V.data.jewelryShops,products=V.data.jewelryProducts;
 const cards=shops.map(shop=>{
  const entries=products.filter(p=>p.shop_id===shop.id),url=location.origin+'/koleksiyon/'+shop.slug;
  return '<div class="card jewelry-shop"><div class="section-title"><div><small class="eyebrow">'+esc(shop.published?'YAYINDA':'TASLAK VİTRİN')+'</small><h2>'+esc(shop.name)+'</h2><p class="muted"><a href="'+esc(url)+'" target="_blank" rel="noopener">'+esc(url)+'</a></p></div><div class="qr-actions">'+(!V.tenantMode?'<button class="btn" onclick="editJewelryShop(\''+shop.id+'\')">Vitrin Ayarları</button><button class="btn" onclick="addJewelryMember(\''+shop.id+'\')">Kullanıcı Ata</button>':'')+'<button class="btn primary" onclick="addJewelryProduct(\''+shop.id+'\')">+ Ürün Ekle</button></div></div><div class="jewelry-products">'+(entries.map(p=>'<div class="jewelry-product"><div><b>'+esc(p.title)+'</b><small>'+esc(JEWELRY_CATEGORIES[p.category]||p.category)+' · '+esc(p.style==='model'?'Model üzerinde':'Stüdyo')+' · '+esc(({draft:'Fotoğraf bekliyor / taslak',generating:'Görsel üretiliyor',review:'Onay bekliyor',published:'Yayında'})[p.status]||p.status)+' · '+esc(p.generation_count)+'/2 üretim</small></div><div class="qr-actions"><button class="btn" onclick="previewJewelryProduct(\''+p.id+'\')">İncele</button>'+(!p.source_path?'<button class="btn" onclick="attachJewelryPhoto(\''+p.id+'\')">Fotoğraf Yükle</button>':'')+(p.source_path&&p.generation_count<2&&['draft','review'].includes(p.status)?'<button class="btn" onclick="generateJewelryProduct(\''+p.id+'\')">AI Görsel Üret</button>':'')+(p.status==='review'?'<button class="btn primary" onclick="reviewJewelryProduct(\''+p.id+'\')">Onayla ve Yayınla</button>':'')+'</div></div>').join('')||'<p class="muted">Bu kuyumcu için henüz ürün yok.</p>')+'</div></div>';
 }).join('');
 return layout('<div class="card jewelry-intro"><div class="section-title"><div><div class="eyebrow">KUYUM · ÜRÜN YAYINI</div><h2>Ürün stüdyosu ve vitrin</h2><p>Telefon fotoğrafını yükleyin, iki stilden birini seçin. Üretilen görseli ürünün taş, ayar, renk ve oranlarıyla karşılaştırıp onaylayın; onaysız ürün vitrinde görünmez.</p></div>'+(!V.tenantMode?'<button class="btn primary" onclick="addJewelryShop()">+ Kuyumcu Vitrini</button>':'')+'</div></div>'+(cards||'<div class="card">Henüz erişebileceğiniz bir kuyumcu vitrini yok.</div>'),'Kuyumcu Stüdyosu','YÖNETİM · ÜRÜN VE YAYIN');
}
function addJewelryMember(shop){modal('Kuyumcu Kullanıcısı Ata','<p>Önce uygulamada hesap açmış kullanıcının e-posta adresini girin. Erişim yalnız bu kuyumcuya verilir.</p><div class="form"><label>E-posta<input id="jmEmail" type="email" autocomplete="email"></label></div>','<button class="btn" onclick="closeModal()">Vazgeç</button><button class="btn primary" onclick="saveJewelryMember(\''+shop+'\')">Ata</button>')}
async function saveJewelryMember(shop){const email=val('jmEmail');try{const {data:{session}}=await CLOUD.auth.getSession();const response=await fetch('/api/jewelry',{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+session.access_token},body:JSON.stringify({action:'member',shop,email})});const result=await response.json();if(!response.ok)throw Error(result.error==='account_not_found'?'Önce bu e-posta ile uygulama hesabı açılmalı.':result.error);closeModal();alert('Kullanıcı yalnız bu kuyumcu vitrini için atandı.')}catch(e){cloudErr(e)}}
function addJewelryShop(){
 const clients=V.data.clients.filter(c=>c.sector==='kuyum'&&c.status==='aktif'&&!V.data.jewelryShops.some(s=>s.client_id===c.id));
 if(!clients.length)return alert('Önce aktif bir kuyumcu müşterisi ekleyin. Her müşteriye bir vitrin açılır.');
 modal('Kuyumcu Vitrini Aç','<div class="form"><label>Kuyumcu<select id="jsClient">'+clients.map(c=>'<option value="'+c.id+'">'+esc(c.name)+'</option>').join('')+'</select></label><label>Vitrin adı<input id="jsName" maxlength="120" placeholder="Mağaza adı"></label><label>Kısa tanıtım<input id="jsTagline" maxlength="200"></label><label>WhatsApp (ülke koduyla)<input id="jsWhatsapp" inputmode="tel" placeholder="905xxxxxxxxx"></label></div>','<button class="btn" onclick="closeModal()">Vazgeç</button><button class="btn primary" onclick="saveJewelryShop()">Vitrin Aç</button>');
}
async function saveJewelryShop(){
 const client=val('jsClient'),name=val('jsName');if(name.length<2||!client)return alert('Kuyumcu ve vitrin adı gerekli.');
 const whatsapp=val('jsWhatsapp').replace(/\D/g,'');if(whatsapp&&!/^\d{10,15}$/.test(whatsapp))return alert('WhatsApp numarasını ülke koduyla girin.');
 const slug='kuyum-'+crypto.randomUUID().slice(0,12),{error}=await CLOUD.from('jewelry_shops').insert({client_id:client,slug,name,tagline:val('jsTagline'),whatsapp});
 if(error)return cloudErr(error);closeModal();await refresh();
}
function editJewelryShop(id){const s=V.data.jewelryShops.find(x=>x.id===id);if(!s)return;
 modal('Vitrin Ayarları','<div class="form"><label>Ad<input id="jsEditName" maxlength="120" value="'+esc(s.name)+'"></label><label>Kısa tanıtım<input id="jsEditTagline" maxlength="200" value="'+esc(s.tagline)+'"></label><label>WhatsApp<input id="jsEditWhatsapp" inputmode="tel" value="'+esc(s.whatsapp)+'"></label><label>Vitrin<select id="jsEditPublished"><option value="false">Gizli</option><option value="true">Yayında</option></select></label></div><p class="muted">Vitrini açmak, yalnızca onaylanmış ürünleri gösterir.</p>','<button class="btn" onclick="closeModal()">Vazgeç</button><button class="btn primary" onclick="saveJewelryShopEdit(\''+id+'\')">Kaydet</button>');document.getElementById('jsEditPublished').value=String(s.published);
}
async function saveJewelryShopEdit(id){const name=val('jsEditName'),whatsapp=val('jsEditWhatsapp').replace(/\D/g,'');if(name.length<2||whatsapp&&!/^\d{10,15}$/.test(whatsapp))return alert('Vitrin adı veya WhatsApp numarası geçersiz.');
 const {error}=await CLOUD.from('jewelry_shops').update({name,tagline:val('jsEditTagline'),whatsapp,published:val('jsEditPublished')==='true',updated_at:new Date().toISOString()}).eq('id',id);if(error)return cloudErr(error);closeModal();await refresh();
}
function addJewelryProduct(shopId){modal('Yeni Mücevher','<div class="form"><label>Ürün adı<input id="jpTitle" maxlength="160"></label><label>Kategori<select id="jpCategory">'+Object.entries(JEWELRY_CATEGORIES).map(([v,n])=>'<option value="'+v+'">'+n+'</option>').join('')+'</select></label><label>Görsel stili<select id="jpStyle"><option value="studio">Zarif stüdyo</option><option value="model">Model üzerinde</option></select></label><label>Ürün notu<input id="jpDescription" maxlength="500" placeholder="Malzeme ve ayırt edici detaylar"></label><label>Ürünün gerçek fotoğrafı<input id="jpSource" type="file" accept="image/jpeg,image/png,image/webp"></label></div><p class="muted">En fazla 10 MB JPG, PNG veya WebP. Ürün doğruluğunu yayın öncesi gözle kontrol edin.</p>','<button class="btn" onclick="closeModal()">Vazgeç</button><button class="btn primary" onclick="saveJewelryProduct(\''+shopId+'\')">Kaydet ve Yükle</button>')}
async function saveJewelryProduct(shopId){
 const title=val('jpTitle'),file=document.getElementById('jpSource')?.files?.[0],types={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'};
 if(title.length<2||!file||!types[file.type]||file.size>10485760)return alert('Ürün adı ve en fazla 10 MB geçerli fotoğraf gerekli.');
 const {data:{user}}=await CLOUD.auth.getUser();const {data,error}=await CLOUD.from('jewelry_products').insert({shop_id:shopId,title,category:val('jpCategory'),style:val('jpStyle'),description:val('jpDescription'),created_by:user.id}).select('id').single();
 if(error)return cloudErr(error);const path=shopId+'/'+data.id+'/source.'+types[file.type];const upload=await CLOUD.storage.from('jewelry-private').upload(path,file,{contentType:file.type,upsert:false});
 if(upload.error){closeModal();await refresh();return cloudErr(Error('Ürün taslağı kaydedildi, fotoğraf yüklenemedi: '+upload.error.message))}
 const saved=await CLOUD.from('jewelry_products').update({source_path:path}).eq('id',data.id);if(saved.error)return cloudErr(saved.error);closeModal();await refresh();
}
function attachJewelryPhoto(id){modal('Ürün Fotoğrafı Yükle','<div class="form"><label>Gerçek ürün fotoğrafı<input id="jpRetrySource" type="file" accept="image/jpeg,image/png,image/webp"></label></div>','<button class="btn" onclick="closeModal()">Vazgeç</button><button class="btn primary" onclick="saveJewelryPhoto(\''+id+'\')">Yükle</button>')}
async function saveJewelryPhoto(id){const p=V.data.jewelryProducts.find(x=>x.id===id),file=document.getElementById('jpRetrySource')?.files?.[0],types={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'};if(!p||p.source_path||!file||!types[file.type]||file.size>10485760)return alert('En fazla 10 MB geçerli ürün fotoğrafı seçin.');const path=p.shop_id+'/'+p.id+'/source.'+types[file.type];const uploaded=await CLOUD.storage.from('jewelry-private').upload(path,file,{contentType:file.type,upsert:false});if(uploaded.error)return cloudErr(uploaded.error);const {error}=await CLOUD.from('jewelry_products').update({source_path:path}).eq('id',id);if(error)return cloudErr(error);closeModal();await refresh()}
async function jewelryImage(path){if(!path)return null;const {data,error}=await CLOUD.storage.from('jewelry-private').createSignedUrl(path,300);if(error)throw error;return data.signedUrl}
async function previewJewelryProduct(id){const p=V.data.jewelryProducts.find(x=>x.id===id);if(!p)return;
 try{const source=await jewelryImage(p.source_path),candidate=await jewelryImage(p.candidate_path);modal('Ürünü İncele','<div class="jewelry-compare"><div><h3>Gerçek fotoğraf</h3>'+(source?'<img src="'+esc(source)+'" alt="Yüklenen orijinal ürün">':'<p>Fotoğraf yüklenemedi.</p>')+'</div><div><h3>AI taslağı</h3>'+(candidate?'<img src="'+esc(candidate)+'" alt="Onay bekleyen görsel">':'<p>Henüz AI görseli oluşturulmadı.</p>')+'</div></div><p class="muted">Görsel üretimi taş sayısı, metal rengi veya ürüne özgü detayları değiştirebilir. Yayınlamadan önce karşılaştırın.</p>','<button class="btn" onclick="closeModal()">Kapat</button>'+(p.status==='review'?'<button class="btn primary" onclick="reviewJewelryProduct(\''+id+'\')">Onay Ekranı</button>':''))}catch(e){cloudErr(e)}
}
async function jewelryAction(id,action){const {data:{session}}=await CLOUD.auth.getSession();if(!session?.access_token)throw Error('Oturum gerekli');const response=await fetch('/api/jewelry',{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+session.access_token},body:JSON.stringify({id,action})});const result=await response.json();if(!response.ok)throw Error(result.error||'İşlem başarısız');return result}
async function generateJewelryProduct(id){const p=V.data.jewelryProducts.find(x=>x.id===id);if(!p?.source_path)return;if(!confirm('Gerçek ürün fotoğrafı AI görsel üretim servisine gönderilecek. API kullanım ücreti doğurabilir. Devam edilsin mi?'))return;
 try{const result=await jewelryAction(id,'generate');await refresh();await previewJewelryProduct(id)}catch(e){cloudErr(e)}
}
async function reviewJewelryProduct(id){const p=V.data.jewelryProducts.find(x=>x.id===id);if(!p?.candidate_path)return;
 try{const [source,candidate]=await Promise.all([jewelryImage(p.source_path),jewelryImage(p.candidate_path)]);modal('Ürün Onayı','<div class="jewelry-compare"><div><h3>Orijinal</h3><img src="'+esc(source)+'" alt="Orijinal mücevher"></div><div><h3>Yayınlanacak</h3><img src="'+esc(candidate)+'" alt="AI görseli"></div></div><label class="jewelry-approval"><input id="jpApproved" type="checkbox"> Taş sayısı, taş şekli, montür, metal rengi ve oranları orijinal ürünle karşılaştırdım; görseli yayınlamayı onaylıyorum.</label>','<button class="btn" onclick="closeModal()">Vazgeç</button><button class="btn primary" onclick="publishJewelryProduct(\''+id+'\')">Onayla ve Yayınla</button>')}catch(e){cloudErr(e)}
}
async function publishJewelryProduct(id){if(!document.getElementById('jpApproved')?.checked)return alert('Önce ürün doğruluğu onayını işaretleyin.');try{await jewelryAction(id,'publish');closeModal();await refresh()}catch(e){cloudErr(e)}}
