const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const context=vm.createContext({window:{VertexCloud:{}},document:{addEventListener(){},getElementById:()=>({value:''})},console,URL,location:{origin:'https://example.test'},sessionStorage:{getItem:()=>null}});
for(const file of ['jewelry-admin.js','jewelry-operations.js','app.js','management-operations.js'])vm.runInContext(fs.readFileSync(file,'utf8').replace(/bootstrap\(\);\s*$/,''),context,{filename:file});
assert.equal(vm.runInContext("resolveQRPurpose('whatsapp','+90 555 555 55 55')",context),'https://wa.me/905555555555');
assert.equal(vm.runInContext("resolveQRPurpose('instagram','@vertex')",context),'https://www.instagram.com/vertex/');
for(const [purpose,value] of [['tour','javascript:alert(1)'],['location','https://evil.test'],['review','https://evil.test'],['tour','https://name:pass@example.test']])assert.throws(()=>vm.runInContext(`resolveQRPurpose(${JSON.stringify(purpose)},${JSON.stringify(value)})`,context));
assert.equal(vm.runInContext("subscriptionDueState({status:'active',next_renewal:'2026-10-01'},'2026-10-01').kind",context),'today');
assert.equal(vm.runInContext("subscriptionDueState({status:'active',next_renewal:'2026-09-30'},'2026-10-01').days",context),-1);
assert.equal(vm.runInContext("subscriptionDueState({status:'active',next_renewal:'2026-10-08'},'2026-10-01').kind",context),'soon');
assert.equal(vm.runInContext("subscriptionDueState({status:'cancelled',next_renewal:'2026-09-30'},'2026-10-01').kind",context),'inactive');
vm.runInContext("layout=(html)=>html;V.tenantMode=true;V.data.jewelryShops=[{id:'s',name:'Test',slug:'test-shop',image_credits:0}];V.data.jewelryProducts=[]",context);
const tenant=vm.runInContext('jewelryStudio()',context);assert(!tenant.includes('Kullanıcı Ata'));assert(!tenant.includes('Vitrin Ayarları'));assert(tenant.includes('Ürün Ekle'));
assert.equal(vm.runInContext('jewelryPriceEstimate(10,18,1000,500,20).total',context),9600);
assert.throws(()=>vm.runInContext('jewelryPriceEstimate(-1,18,1000,0,20)',context));
assert.throws(()=>vm.runInContext('jewelryPriceEstimate(1,16,1000,0,20)',context));
const api=require('../api/jewelry');process.env.SUPABASE_SECRET_KEY='sb_secret_fixture';
const response=()=>({code:0,data:null,setHeader(){},status(n){this.code=n;return this},json(data){this.data=data;return this}});
(async()=>{let r=response();await api({method:'POST',headers:{},body:{action:'generate',id:'00000000-0000-0000-0000-000000000000'}},r);assert.equal(r.code,401);let calls=0;global.fetch=async(url)=>{calls++;const path=String(url);if(path.includes('jewelry_shops?'))return {ok:true,text:async()=>JSON.stringify([{id:'s',name:'Shop',phrases:['a','b','c','d']}])};if(path.includes('jewelry_products?'))return {ok:true,text:async()=>JSON.stringify([{id:'p',title:'Item',category:'yuzuk',description:'',public_path:'s/p.png',phrase_index:0,video_status:'draft'}])};return {ok:true,text:async()=>JSON.stringify([])}};r=response();await api({method:'GET',headers:{},query:{action:'catalog',slug:'test-shop'}},r);assert.equal(r.code,200);assert.equal(r.data.products.length,1);assert(!('source_path' in r.data.products[0]));assert(!('candidate_path' in r.data.products[0]));assert(calls>=3);console.log('PASS: QR destination validation, tenant controls, anonymous API denial, public catalog privacy. Mocked checks; no provider call.');})().catch(e=>{console.error(e);process.exitCode=1});
